---
sidebar: sidebar 
permalink: br-start-discover-kubernetes.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Kubernetes 
summary: Der BlueXP backup and recovery muss zunächst die Arbeitslasten erkennen, damit Sie den Dienst nutzen können. 
---
= Entdecken Sie Kubernetes-Workloads in BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Der BlueXP backup and recovery muss zuerst Kubernetes-Workloads erkennen, damit Sie den Dienst nutzen können.

*Erforderliche BlueXP -Rolle* Diese Aufgabe erfordert die Superadministratorrolle „Backup und Wiederherstellung“ der Datendienste.  Erfahren Sie mehr überlink:reference-roles.html["Rollen und Berechtigungen für Datendienste zur Sicherung und Wiederherstellung"] . https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über BlueXP-Zugriffsrollen für alle Dienste"^] .



== Entdecken Sie Kubernetes-Workloads

Im Backup- und Recovery-Inventar können Sie Kubernetes-Workloads erkennen, die in Ihrer Umgebung ausgeführt werden. Durch die Erkennung eines Workloads wird BlueXP backup and recovery ein Kubernetes-Cluster hinzugefügt. So können Sie Anwendungen zum Cluster hinzufügen und die im Cluster gehosteten Ressourcen schützen.

.Schritte
. Führen Sie einen der folgenden Schritte aus:
+
** Wenn Sie Kubernetes-Workloads zum ersten Mal erkennen, wählen Sie in BlueXP backup and recovery unter dem Kubernetes-Workload-Typ „Erkennen und verwalten“ aus.
** Wenn Sie Kubernetes-Workloads bereits erkannt haben, wählen Sie in BlueXP backup and recovery*Inventar* > *Workloads* und dann *Ressourcen erkennen*.


. Wählen Sie den Workloadtyp *Kubernetes* aus.
. Geben Sie einen Clusternamen ein und wählen Sie einen Connector zur Verwendung mit dem Cluster aus.
. Befolgen Sie die angezeigten Befehlszeilenanweisungen:
+
** Erstellen Sie einen Trident Schutznamespace
** Erstellen eines Kubernetes-Geheimnisses
** Hinzufügen eines Helm-Repositorys
** Installieren Sie Trident Protect und den Trident Protect-Anschluss
+
Diese Schritte stellen sicher, dass die BlueXP backup and recovery mit dem Cluster interagieren kann.



. Nachdem Sie die Schritte abgeschlossen haben, wählen Sie *Entdecken*.
+
Der Cluster wird zum Inventar hinzugefügt.

. Wählen Sie in der zugehörigen Kubernetes-Workload „Anzeigen“ aus, um die Liste der Anwendungen, Cluster und Namespaces für diese Workload anzuzeigen.




== Weiter zum BlueXP backup and recovery -Dashboard

Um das BlueXP backup and recovery anzuzeigen, befolgen Sie diese Schritte.

. Wählen Sie im oberen Menü *Dashboard* aus.
. Überprüfen Sie den Zustand des Datenschutzes. Die Anzahl der gefährdeten oder geschützten Workloads steigt basierend auf den neu erkannten, geschützten und gesicherten Workloads.
+
link:br-use-dashboard.html["Erfahren Sie, was Ihnen das Dashboard anzeigt"].


