---
sidebar: sidebar 
permalink: br-start-setup.html 
keywords: bluexp, backup, back up, restore, recovery, aws, azure 
summary: Bevor Sie die BlueXP backup and recovery verwenden, führen Sie einige Schritte aus, um Sicherungsziele einzurichten. 
---
= Richten Sie Sicherungsziele ein, bevor Sie BlueXP backup and recovery verwenden
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Bevor Sie die BlueXP backup and recovery verwenden, führen Sie einige Schritte aus, um Sicherungsziele einzurichten.

Prüfen Sie vor dem Startenlink:concept-start-prereq.html["Voraussetzungen"], ob Ihre Umgebung für Sie bereit ist.



== Bereiten Sie das Sicherungsziel vor

Bereiten Sie eines oder mehrere der folgenden Sicherungsziele vor:

* NetApp StorageGRID.
+
Siehe https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["Entdecken Sie StorageGRID"^].

+
Siehe https://docs.netapp.com/us-en/storagegrid/index.html["StorageGRID-Dokumentation"^] für Details zu StorageGRID.

* Amazon Web Services. Siehe https://docs.netapp.com/us-en/bluexp-s3-storage/index.html["Amazon S3-Dokumentation"^].
+
Gehen Sie wie folgt vor, um AWS als Sicherungsziel vorzubereiten:

+
** Richten Sie ein Konto in AWS ein.
** Konfigurieren Sie die S3-Berechtigungen in AWS, die im nächsten Abschnitt aufgeführt sind.
** Weitere Informationen zum Management von AWS-Storage in BlueXP  finden Sie unter https://docs.netapp.com/us-en/bluexp-setup-admin/task-viewing-amazon-s3.html["Amazon S3 Buckets managen"^].




* Microsoft Azure.
+
** Siehe https://docs.netapp.com/us-en/bluexp-azure-netapp-files/index.html["Azure NetApp Files-Dokumentation"^].
** Richten Sie ein Konto in Azure ein.
** Konfigurieren  https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["Azure-Berechtigungen"^] in Azure.
** Weitere Informationen zur Verwaltung Ihres Azure-Speichers in BlueXP finden Sie unter  https://docs.netapp.com/us-en/bluexp-blob-storage/task-view-azure-blob-storage.html["Managen Sie Ihre Azure Storage-Konten"^] .




Nachdem Sie die Optionen im Sicherungsziel selbst konfiguriert haben, konfigurieren Sie es später als Sicherungsziel im BlueXP backup and recovery . Weitere Informationen zur Konfiguration des Sicherungsziels in BlueXP backup and recovery finden Sie unter link:br-start-discover-backup-targets.html["Ermitteln von Sicherungszielen"] .



== Richten Sie S3-Berechtigungen ein

Sie müssen zwei Sätze von AWS S3-Berechtigungen konfigurieren:

* Berechtigungen für den Connector zum Erstellen und Managen des S3-Buckets.
* Berechtigungen für den On-Premises-ONTAP-Cluster, damit er Daten lesen und in den S3-Bucket schreiben kann


.Schritte
. Stellen Sie sicher, dass der Connector über die erforderlichen Berechtigungen verfügt. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-aws.html["Berechtigungen für BlueXP -Richtlinien"].
+

NOTE: Beim Erstellen von Backups in AWS China-Regionen müssen Sie den AWS-Ressourcennamen „arn“ unter allen _Resource_-Abschnitten in den IAM-Richtlinien von „aws“ in „aws-cn“ ändern, z. B. `arn:aws-cn:s3:::netapp-backup-*`.

. Wenn Sie den Dienst aktivieren, werden Sie vom Backup-Assistenten aufgefordert, einen Zugriffsschlüssel und einen geheimen Schlüssel einzugeben. Diese Anmeldedaten werden an den ONTAP-Cluster weitergeleitet, damit ONTAP Daten im S3-Bucket sichern und wiederherstellen kann. Dazu müssen Sie einen IAM-Benutzer mit den folgenden Berechtigungen erstellen.
+
Siehe https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["AWS Documentation: Erstellen einer Rolle zum Delegieren von Berechtigungen an einen IAM-Benutzer"^].

+
[%collapsible]
====
[source, json]
----
{
    "Version": "2012-10-17",
     "Statement": [
        {
           "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListBucket",
                "s3:ListAllMyBuckets",
                "s3:GetBucketLocation",
                "s3:PutEncryptionConfiguration"
            ],
            "Resource": "arn:aws:s3:::netapp-backup-*",
            "Effect": "Allow",
            "Sid": "backupPolicy"
        },
        {
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::netapp-backup*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListAllMyBuckets",
                "s3:PutObjectTagging",
                "s3:GetObjectTagging",
                "s3:RestoreObject",
                "s3:GetBucketObjectLockConfiguration",
                "s3:GetObjectRetention",
                "s3:PutBucketObjectLockConfiguration",
                "s3:PutObjectRetention"
            ],
            "Resource": "arn:aws:s3:::netapp-backup*/*",
            "Effect": "Allow"
        }
    ]
}
----
====

