---
sidebar: sidebar 
permalink: br-start-licensing.html 
keywords: license, licensing, updating license, paygo license, byol license, nlf, license generator, backup license, add backup license, update backup license, annual, netapp intelligent services 
summary: Sie können BlueXP Backup und Recovery lizenzieren, indem Sie ein Pay-as-you-go- oder ein jährliches Marketplace-Abonnement von Ihrem Cloud-Provider erwerben oder eine Bring-Your-Own-License von NetApp erwerben. Um das Backup und Recovery von BlueXP in einer Arbeitsumgebung zu aktivieren, Backups Ihrer Produktionsdaten zu erstellen und Backup-Daten auf einem Produktionssystem wiederherzustellen, ist eine gültige Lizenz erforderlich. 
---
= Lizenzierung für Backup und Recovery von BlueXP einrichten
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können BlueXP  Backup und Recovery lizenzieren, indem Sie ein Pay-as-you-go- (PAYGO) oder ein jährliches Marketplace-Abonnement für *NetApp Intelligent Services* von Ihrem Cloud-Provider erwerben oder ein BYOL-Abonnement (Bring-Your-Own-License) von NetApp erwerben. Um das Backup und Recovery von BlueXP in einer Arbeitsumgebung zu aktivieren, Backups Ihrer Produktionsdaten zu erstellen und Backup-Daten auf einem Produktionssystem wiederherzustellen, ist eine gültige Lizenz erforderlich.

Ein paar Notizen, bevor Sie weitere lesen:

* Wenn Sie auf dem Marketplace Ihres Cloud-Providers für ein Cloud Volumes ONTAP-System bereits ein PAYGO-Abonnement (Pay-as-you-go) abonniert haben, haben Sie auch das Backup und Recovery von BlueXP automatisch abonniert. Sie müssen sich nicht erneut anmelden.
* Das BYOL (Bring-Your-Own-License) von BlueXP  für Backup und Recovery ist eine Floating Lizenz, die Sie über alle Systeme Ihres BlueXP  Unternehmens oder Kontos hinweg verwenden können. Wenn also über ausreichende Backup-Kapazität mit einer bestehenden BYOL-Lizenz verfügen, müssen Sie keine weitere BYOL-Lizenz erwerben.
* Wenn Sie eine BYOL-Lizenz verwenden, empfehlen wir Ihnen, auch ein PAYGO Abonnement zu abonnieren. Wenn Sie mehr Daten sichern, als durch Ihre BYOL-Lizenz zulässig ist, oder wenn die Laufzeit Ihrer Lizenz abläuft, wird das Backup über Ihr Pay-as-you-go-Abonnement fortgesetzt – der Service wird nicht unterbrochen.
* Beim Backup von lokalen ONTAP-Daten in StorageGRID ist eine BYOL-Lizenz erforderlich. Es entstehen jedoch keine Kosten für Cloud-Provider-Storage.


link:concept-backup-to-cloud.html["Erfahren Sie mehr über die Kosten für die Nutzung von BlueXP Backup und Recovery."]



== 30 Tage kostenlos testen mit unserer

Wenn Sie sich für ein Pay-as-you-go-Abonnement auf dem Markt Ihres Cloud-Anbieters für *NetApp Intelligente Dienste* anmelden, steht Ihnen eine kostenlose 30-Tage-Testversion von BlueXP  Backup und Recovery zur Verfügung. Die kostenlose Testversion beginnt zu dem Zeitpunkt, zu dem Sie die Marketplace-Liste abonnieren. Beachten Sie, dass Sie bei der Implementierung eines Cloud Volumes ONTAP Systems, wenn Sie für das Marketplace-Abonnement zahlen und dann 10 Tage später die kostenlose Testversion von BlueXP Backup und Recovery starten, noch 20 Tage für die kostenlose Testversion haben.

Nach Ablauf der kostenlosen Testversion werden Sie automatisch und ohne Unterbrechung auf das PAYGO-Abonnement umgeschaltet. Wenn Sie sich dazu entschließen, BlueXP backup and recovery nicht weiter zu verwenden, link:prev-ontap-backup-manage.html["Heben Sie die Registrierung von BlueXP Backup und Recovery aus der Betriebsumgebung auf"] bevor die Testphase endet und es werden Ihnen keine Kosten berechnet.



=== Beenden Sie die kostenlose Testversion

Wenn Sie BlueXP backup and recovery nach Ablauf der kostenlosen Testversion weiterhin verwenden möchten, müssen Sie ein kostenpflichtiges Abonnement einrichten.  Sie können dies über die BlueXP Schnittstelle tun, indem Sie zum Abschnitt „Abrechnung“ navigieren und ein Abonnement auswählen, das Ihren Anforderungen entspricht.  Wenn Sie BlueXP backup and recovery nicht weiter verwenden möchten, können Sie die kostenlose Testversion beenden.

Wenn Sie die kostenlose Testversion beenden, ohne einen kostenpflichtigen Plan zu abonnieren, werden Ihre Daten 60 Tage nach Ablauf der kostenlosen Testversion automatisch gelöscht.  Optional können Sie Ihre Daten auch sofort vom System löschen lassen.

.Schritte
. Wählen Sie auf der Zielseite für BlueXP backup and recovery *Kostenlose Testversion anzeigen* aus.
. Wählen Sie *Kostenlose Testversion beenden*.
. Wählen Sie *Daten sofort nach Beendigung meiner kostenlosen Testversion löschen*, um Ihre Daten sofort zu löschen.
. Geben Sie *Testversion beenden* in das Feld ein.
. Wählen Sie zur Bestätigung *Ende*.




== Nutzen Sie ein BlueXP PAYGO-Abonnement für Backup und Recovery

Beim nutzungsbasierten Modell bezahlen Sie Ihren Cloud-Provider für Objekt-Storage-Kosten und für NetApp Backup-Lizenzen auf Stundenbasis in einem einzigen Abonnement. Sie sollten *NetApp Intelligente Dienste* auf dem Marktplatz abonnieren, auch wenn Sie eine kostenlose Testversion haben oder wenn Sie Ihre eigene Lizenz (BYOL) mitbringen:

* Durch die Anmeldung wird sichergestellt, dass nach der kostenlosen Testversion keine Serviceunterbrechung erfolgt. Nach Ablauf der Testversion werden Ihnen die Daten, die Sie sichern, stündlich in Rechnung gestellt.
* Wenn Sie mehr Daten sichern, als durch Ihre BYOL-Lizenz zulässig, werden die Backup- und Restore-Vorgänge über Ihr Pay-as-you-go-Abonnement fortgesetzt. Wenn Sie beispielsweise eine 10-tib-BYOL-Lizenz haben, wird die gesamte Kapazität über den 10 tib Speicherplatz durch das PAYGO-Abonnement berechnet.


Ihr Pay-as-you-go-Abonnement wird während der kostenlosen Testversion nicht in Rechnung gestellt, oder wenn die BYOL-Lizenz nicht überschritten wurde.

Es gibt einige PAYGO-Pläne für das Backup und Recovery von BlueXP:

* Paket „Cloud Backup“, mit dem Sie Cloud Volumes ONTAP Daten und ONTAP Daten vor Ort sichern können
* Ein „CVO Professional“-Paket, mit dem Sie Backup und Recovery von Cloud Volumes ONTAP und BlueXP bündeln können. Dazu zählen unbegrenzte Backups für das Cloud Volumes ONTAP-System mit der Lizenz (die Backup-Kapazität wird nicht von der lizenzierten Kapazität erfasst). Mit dieser Option können Sie kein Backup von lokalen ONTAP Daten erstellen.
+
Beachten Sie, dass für diese Option auch ein PAYGO-Abonnement für Backup und Recovery erforderlich ist, für qualifizierte Cloud Volumes ONTAP-Systeme fallen jedoch keine Gebühren an.



https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#capacity-based-licensing["Erfahren Sie mehr über diese kapazitätsbasierten Lizenzpakete"].

Verwenden Sie diese Links, um BlueXP Backup und Recovery über den Marketplace Ihres Cloud-Providers zu abonnieren:

ifdef::aws[]

* AWS:  https://aws.amazon.com/marketplace/pp/prodview-oorxakq6lq7m4["Weitere Informationen zu den Preisen finden Sie im Marktplatz-Angebot für intelligente NetApp-Dienste"^] .endif::aws[]


ifdef::azure[]

* Azurblau:  https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-manager?tab=Overview["Weitere Informationen zu den Preisen finden Sie im Marktplatz-Angebot für intelligente NetApp-Dienste"^] .endif::azure[]


ifdef::gcp[]

* Google Cloud:  https://console.cloud.google.com/marketplace/details/netapp-cloudmanager/cloud-manager?supportedpurview=project["Weitere Informationen zu den Preisen finden Sie im Marktplatz-Angebot für intelligente NetApp-Dienste"^] .endif::gcp[]




== Verwenden Sie einen Jahresvertrag

Jährliche Zahlung für BlueXP Backup und Recovery durch Erwerb eines Jahresvertrags Das Angebot ist mit Laufzeiten von 1, 2 oder 3 Jahren erhältlich.

Wenn Sie einen Jahresvertrag von einem Markt haben, wird der gesamte Verbrauch von BlueXP Backup und Recovery mit diesem Vertrag in Rechnung gestellt. Es ist nicht möglich, einen jährlichen Marktvertrag mit einem BYOL-Modell zu kombinieren.

ifdef::aws[]

Wenn Sie AWS verwenden, stehen Ihnen zwei Jahresverträge zur Verfügung von  https://aws.amazon.com/marketplace/pp/prodview-q7dg6zwszplri["AWS Marketplace Seite"^] für Cloud Volumes ONTAP und lokale ONTAP Systeme:

* Ein Plan für „Cloud Backup“, mit dem Sie Backups von Cloud Volumes ONTAP Daten und ONTAP Daten vor Ort erstellen können
+
Wenn Sie diese Option verwenden möchten, richten Sie Ihr Abonnement auf der Marketplace-Seite ein und dann https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-aws-accounts.html#associate-an-aws-subscription["Verbinden Sie das Abonnement mit Ihren AWS Zugangsdaten"^]. Beachten Sie, dass Sie außerdem für Ihre Cloud Volumes ONTAP Systeme mit diesem Jahresabonnement zahlen müssen, da Sie Ihren AWS Zugangsdaten in BlueXP nur ein aktives Abonnement zuweisen können.

* Ein „CVO Professional“-Plan, mit dem Sie Backup und Recovery von Cloud Volumes ONTAP und BlueXP bündeln können. Dazu zählen unbegrenzte Backups für das Cloud Volumes ONTAP-System mit der Lizenz (die Backup-Kapazität wird nicht von der lizenzierten Kapazität erfasst). Mit dieser Option können Sie kein Backup von lokalen ONTAP Daten erstellen.
+
Siehe https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Cloud Volumes ONTAP-Lizenzthema"^] Erfahren Sie mehr über diese Lizenzoption.

+
Wenn Sie diese Option nutzen möchten, können Sie den Jahresvertrag einrichten, wenn Sie eine Cloud Volumes ONTAP Arbeitsumgebung erstellen und BlueXP Sie auffordert, den AWS Marketplace zu abonnieren. endif::aws[]



ifdef::azure[]

Wenn Sie Azure verwenden, stehen Ihnen zwei Jahresverträge zur Verfügung von der  https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.netapp-bluexp["Azure Marketplace Seite"^] für Cloud Volumes ONTAP und lokale ONTAP Systeme:

* Ein Plan für „Cloud Backup“, mit dem Sie Backups von Cloud Volumes ONTAP Daten und ONTAP Daten vor Ort erstellen können
+
Wenn Sie diese Option verwenden möchten, richten Sie Ihr Abonnement auf der Marketplace-Seite ein und dann https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-azure-accounts.html#subscribe["Ordnen Sie das Abonnement Ihren Azure-Zugangsdaten zu"^]. Beachten Sie, dass Sie außerdem für Ihre Cloud Volumes ONTAP Systeme mit diesem Jahresabonnement zahlen müssen, da Sie Ihren Azure-Zugangsdaten in BlueXP nur ein aktives Abonnement zuweisen können.

* Ein „CVO Professional“-Plan, mit dem Sie Backup und Recovery von Cloud Volumes ONTAP und BlueXP bündeln können. Dazu zählen unbegrenzte Backups für das Cloud Volumes ONTAP-System mit der Lizenz (die Backup-Kapazität wird nicht von der lizenzierten Kapazität erfasst). Mit dieser Option können Sie kein Backup von lokalen ONTAP Daten erstellen.
+
Siehe https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Cloud Volumes ONTAP-Lizenzthema"^] Erfahren Sie mehr über diese Lizenzoption.

+
Wenn Sie diese Option nutzen möchten, können Sie den Jahresvertrag einrichten, wenn Sie eine Cloud Volumes ONTAP Arbeitsumgebung erstellen und BlueXP Sie auffordert, den Azure Marketplace zu abonnieren. endif::azure[]



ifdef::gcp[]

Wenn Sie GCP verwenden, wenden Sie sich an Ihren NetApp Vertriebsmitarbeiter, um einen Jahresvertrag abzuschließen. Der Vertrag ist als Privatangebot im Google Cloud Marketplace erhältlich.

Nachdem NetApp Ihnen das private Angebot mitgeteilt hat, können Sie den Jahresplan auswählen, wenn Sie während der Aktivierung von BlueXP backup and recovery ein Abonnement im Google Cloud Marketplace abschließen. endif::gcp[]



== Verwenden Sie eine BlueXP BYOL-Lizenz für Backup und Recovery

Mit den Bring-Your-Own-License-Lizenzen von NetApp erhalten Sie Vertragsbedingungen mit 1, 2 oder 3 Jahren. Sie bezahlen nur für die Daten, die Sie sichern, berechnet sich anhand der genutzten logischen Kapazität (_before_ any Effizienzfunktionen) der zu sichernden ONTAP Quell-Volumes. Diese Kapazität wird auch als Front-End Terabyte (FETB) bezeichnet.

Die BYOL BlueXP  Backup- und Recovery-Lizenz ist eine Floating-Lizenz, bei der die Gesamtkapazität über alle Systeme, die Ihrer Organisation oder Ihrem BlueXP  Konto zugeordnet sind, hinweg gemeinsam genutzt wird. Bei ONTAP Systemen können Sie eine ungefähre Schätzung der Kapazität erhalten, die Sie benötigen, indem Sie den CLI-Befehl für die Volumes ausführen `volume show -fields logical-used-by-afs`, die Sie sichern möchten.

Wenn Sie keine BlueXP BYOL-Lizenz für Backup und Recovery besitzen, klicken Sie rechts unten in BlueXP auf das Chat-Symbol, um eine zu kaufen.

Wenn Sie optional eine nicht zugewiesene Node-basierte Lizenz für Cloud Volumes ONTAP haben, die Sie nicht verwenden werden, können Sie sie in eine BlueXP Backup- und Recovery-Lizenz mit derselben Dollar-Äquivalenz und demselben Ablaufdatum konvertieren. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html#exchange-unassigned-node-based-licenses["Weitere Informationen finden Sie hier"^].

Sie nutzen das Digital Wallet von BlueXP zum Management von BYOL-Lizenzen. Sie können über das BlueXP Digital Wallet neue Lizenzen hinzufügen, vorhandene Lizenzen aktualisieren und den Lizenzstatus einsehen.

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["Informieren Sie sich über das Hinzufügen von Lizenzen mit Digital Wallet"^].
