---
sidebar: sidebar 
permalink: br-use-protect-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter 
summary: Mit BlueXP backup and recovery können Sie Ihre Workload-Host-Informationen, Datenbankinformationen und Instanzen verwalten. Sie können die Schutzeinstellungen für Ihr Inventar anzeigen, bearbeiten und löschen. 
---
= Kubernetes-Anwendungen hinzufügen und schützen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mit BlueXP backup and recovery können Sie Ihre Kubernetes-Cluster einfach erkennen, ohne Kubeconfig-Dateien erstellen und hochladen zu müssen. Sie können Kubernetes-Cluster verbinden und die benötigte Software mit einfachen Befehlen aus der BlueXP Benutzeroberfläche installieren.

.Erforderliche BlueXP -Rolle
Organisationsadministrator oder SnapCenter Administrator. link:reference-roles.html["Erfahren Sie mehr über die Zugriffsrollen für BlueXP backup and recovery"] .  https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Erfahren Sie mehr über BlueXP-Zugriffsrollen für alle Dienste"^] .



== Hinzufügen und Schützen einer neuen Kubernetes-Anwendung

Der erste Schritt zum Schutz von Kubernetes-Anwendungen besteht darin, eine Anwendung innerhalb von BlueXP backup and recovery zu erstellen. Wenn Sie eine Anwendung erstellen, machen Sie BlueXP auf die laufende Anwendung im Kubernetes-Cluster aufmerksam.

.Bevor Sie beginnen
Bevor Sie eine Kubernetes-Anwendung hinzufügen und schützen können, müssen Sie link:br-start-discover.html["Kubernetes-Workloads entdecken"] .

.Schritte
. Wählen Sie in BlueXP backup and recovery*Inventar* aus.
. Wählen Sie eine Kubernetes-Instanz und wählen Sie *Anzeigen*, um die mit dieser Instanz verknüpften Ressourcen anzuzeigen.
. Wählen Sie die Registerkarte *Anwendungen*.
. Wählen Sie *Anwendung erstellen*.
. Geben Sie einen Namen für die Anwendung ein.
. Wählen Sie optional eines der folgenden Felder aus, um nach den Ressourcen zu suchen, die Sie schützen möchten:
+
** Zugehöriger Cluster
** Zugehörige Namespaces
** Ressourcentypen
** Beschriftungsselektoren


. Wählen Sie optional *Cluster Scoped Resources* aus, um Ressourcen auszuwählen, die auf Clusterebene liegen. Wenn Sie diese einschließen, werden sie der Anwendung beim Erstellen hinzugefügt.
. Wählen Sie optional *Suchen* aus, um die Ressourcen basierend auf Ihren Suchkriterien zu finden.
+

NOTE: BlueXP speichert die Suchparameter oder Ergebnisse nicht; die Parameter werden verwendet, um im ausgewählten Kubernetes-Cluster nach Ressourcen zu suchen, die in die Anwendung eingebunden werden können.

. BlueXP zeigt eine Liste der Ressourcen an, die Ihren Suchkriterien entsprechen.
. Wenn die Liste die Ressourcen enthält, die Sie schützen möchten, wählen Sie *Weiter*.
. Wählen Sie im Bereich *Richtlinie* optional eine vorhandene Schutzrichtlinie zum Schutz der Anwendung aus oder erstellen Sie eine neue Richtlinie. Wenn Sie keine Richtlinie auswählen, wird die Anwendung ohne Schutzrichtlinie erstellt. Sie können später eine Richtlinie hinzufügen.
. Aktivieren und konfigurieren Sie im Bereich *Prescripts und Postscripts* alle Prescript- oder Postscript-Ausführungs-Hooks, die vor oder nach Sicherungsvorgängen ausgeführt werden sollen. Um Prescripts oder Postscripts zu aktivieren, müssen Sie bereits mindestens einen link:br-use-manage-execution-hook-templates.html["Ausführungs-Hook-Vorlage"] .
. Wählen Sie *Erstellen*.


.Ergebnis
Die Anwendung wird erstellt und erscheint in der Anwendungsliste im Reiter *Anwendungen* des Kubernetes-Inventars. BlueXP aktiviert den Schutz der Anwendung basierend auf Ihren Einstellungen, und Sie können den Fortschritt im Bereich *Überwachung* von Backup und Wiederherstellung überwachen.



== Schützen einer vorhandenen Kubernetes-Anwendung

Aktivieren Sie eine Schutzrichtlinie für eine Kubernetes-Anwendung, die Sie bereits hinzugefügt haben.

.Schritte
. Wählen Sie in BlueXP backup and recovery*Inventar* aus.
. Wählen Sie eine Kubernetes-Instanz und wählen Sie *Anzeigen*, um die mit dieser Instanz verknüpften Ressourcen anzuzeigen.
. Wählen Sie die Registerkarte *Anwendungen*.
. Wählen Sie in der Anwendungsliste eine Anwendung aus, die Sie schützen möchten, und wählen Sie das zugehörige Aktionsmenü.
. Wählen Sie *Schutz*.
. Wählen Sie im Bereich *Richtlinie* eine vorhandene Schutzrichtlinie zum Schutz der Anwendung aus oder erstellen Sie eine neue Richtlinie.
. Aktivieren und konfigurieren Sie im Bereich *Prescripts und Postscripts* alle Prescript- oder Postscript-Ausführungs-Hooks, die vor oder nach Sicherungsvorgängen ausgeführt werden sollen. Sie können den Typ des Ausführungs-Hooks, die verwendete Vorlage, Argumente und Label-Selektoren konfigurieren.
. Wählen Sie * Fertig*.


.Ergebnis
BlueXP aktiviert den Anwendungsschutz basierend auf Ihren Einstellungen. Sie können den Fortschritt im Bereich „Überwachung“ von Backup und Wiederherstellung überwachen. Sobald Sie den Anwendungsschutz aktivieren, erstellt BlueXP ein vollständiges Backup der Anwendung. Alle zukünftigen inkrementellen Backups werden basierend auf dem Zeitplan erstellt, den Sie in der zugehörigen Schutzrichtlinie festgelegt haben.



== Sichern Sie jetzt eine Kubernetes-Anwendung

Erstellen Sie manuell eine Sicherung einer Kubernetes-Anwendung, um eine Basis für zukünftige Sicherungen und Snapshots zu schaffen oder um sicherzustellen, dass die aktuellsten Daten geschützt sind.

.Schritte
. Wählen Sie in BlueXP backup and recovery*Inventar* aus.
. Wählen Sie eine Kubernetes-Instanz und wählen Sie *Anzeigen*, um die mit dieser Instanz verknüpften Ressourcen anzuzeigen.
. Wählen Sie die Registerkarte *Anwendungen*.
. Wählen Sie in der Anwendungsliste eine Anwendung aus, die Sie sichern möchten, und wählen Sie das zugehörige Aktionsmenü.
. Wählen Sie *Jetzt sichern*.
. Stellen Sie sicher, dass der richtige Anwendungsname ausgewählt ist.
. Wählen Sie *Backup*.


.Ergebnis
BlueXP erstellt ein Backup der Anwendung und zeigt den Fortschritt im Bereich „Überwachung“ von Backup und Wiederherstellung an. Das Backup wird basierend auf der mit der Anwendung verknüpften Schutzrichtlinie erstellt.
