---
sidebar: sidebar 
permalink: br-use-mssql-restore-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: Sicherungen Ihrer Daten können an den Speicherorten wiederhergestellt werden, an denen Sie Sicherungen erstellt haben. Dazu gehören Snapshots, Replikationen und Sicherungen im Objektspeicher. Überprüfen Sie die Wiederherstellungsorte, Wiederherstellungspunkte und wiederherzustellenden Ressourcentypen. 
---
= Übersicht über die Wiederherstellung von Microsoft SQL-Workloads mithilfe von BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sicherungen Ihrer Microsoft SQL Server-Daten aus BlueXP backup and recovery können von den Speicherorten wiederhergestellt werden, an denen Sie die Sicherungen gespeichert haben: Snapshots, Replikationen oder Sicherungen im Objektspeicher. Sie können einen Workload in der ursprünglichen Arbeitsumgebung, in einer anderen Arbeitsumgebung mit demselben Cloud-Konto oder auf einem lokalen ONTAP System wiederherstellen. Überprüfen Sie die Wiederherstellungsorte, Wiederherstellungspunkte und wiederherzustellenden Ressourcentypen.

.Von diesen Speicherorten wiederherstellen
Sie können Workloads von verschiedenen Startorten wiederherstellen:

* Wiederherstellung von einem primären Speicherort
* Wiederherstellen aus einer replizierten Ressource
* Wiederherstellen aus einer Objektspeichersicherung


.Stellen Sie diese Punkte wieder her
Sie können Daten bis zum letzten Snapshot oder bis zu diesen Punkten wiederherstellen:

* Wiederherstellen aus Snapshots
* Stellen Sie die Datei zu einem bestimmten Zeitpunkt wieder her. Dies ist hilfreich, wenn Sie den Namen und Speicherort der Datei sowie das Datum kennen, an dem sie zuletzt in gutem Zustand war.
* Wiederherstellen der neuesten Sicherung




== Wie es weiter geht

Weitere Informationen zum Wiederherstellen von Workloads finden Sie unter link:br-use-mssql-restore.html["Wiederherstellen von Workloads"] .
