---
sidebar: sidebar 
permalink: br-use-vmware-protect-overview.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Schützen Sie Ihre VMware-Workloads mit NetApp BlueXP backup and recovery. 
---
= Schützen Sie VMware-Workloads mit der BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Schützen Sie Ihre VMware-VMs und Datenspeicher mit BlueXP backup and recovery.  BlueXP backup and recovery bietet schnelle, platzsparende, absturzkonsistente und VM-konsistente Backup- und Wiederherstellungsvorgänge.  Sie können VMware-Workloads auf Amazon Web Services S3 oder StorageGRID sichern und VMware-Workloads auf einem lokalen VMware-Host wiederherstellen.


NOTE: Diese Version von BlueXP backup and recovery unterstützt nur VMware vCenter und erkennt keine vVols oder VMs auf vVols.

Verwenden Sie BlueXP backup and recovery, um eine 3-2-1-Strategie zu implementieren, bei der Sie 3 Kopien Ihrer Quelldaten auf 2 verschiedenen Speichersystemen sowie 1 Kopie in der Cloud haben.  Zu den Vorteilen des 3-2-1-Ansatzes gehören:

* Mehrere Datenkopien bieten mehrschichtigen Schutz vor internen (internen) und externen Cybersicherheitsbedrohungen.
* Mehrere Medientypen gewährleisten die Failover-Möglichkeit bei einem physischen oder logischen Ausfall eines Medientyps.
* Die Vor-Ort-Kopie ermöglicht eine schnelle Wiederherstellung, wobei die Offsite-Kopien für den Fall verfügbar sind, dass die Vor-Ort-Kopie kompromittiert wird.


[]
====
*HINWEIS* Informationen zum Umschalten zwischen den BlueXP backup and recovery -UI-Versionen finden Sie unter link:br-start-switch-ui.html["Wechseln Sie zur vorherigen BlueXP backup and recovery"] .

====
Sie können BlueXP backup and recovery verwenden, um die folgenden Aufgaben im Zusammenhang mit VMware-Workloads auszuführen:

* link:br-use-vmware-discovery.html["Entdecken Sie VMware-Workloads"]
* link:br-use-vmware-protection-groups.html["Erstellen und Verwalten von Schutzgruppen für VMware-Workloads"]
* link:br-use-vmware-backup.html["Sichern Sie VMware-Workloads"]
* link:br-use-vmware-restore.html["Wiederherstellen von VMware-Workloads"]

