---
sidebar: sidebar 
permalink: br-use-kubernetes-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: Sie können Kubernetes-Anwendungen und Anwendungsdaten von lokalen ONTAP -Systemen auf Amazon Web Services, Microsoft Azure, Google Cloud Platform und StorageGRID schützen und so sicherstellen, dass Ihre Daten geschützt sind. 
---
= Übersicht über die Verwaltung von Kubernetes-Workloads
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Durch die Verwaltung von Kubernetes-Workloads in BlueXP backup and recovery können Sie Ihre Kubernetes-Cluster und -Anwendungen zentral verwalten und schützen. Sie können die von Ihren Kubernetes-Clustern gehosteten Ressourcen und Anwendungen verwalten. Außerdem können Sie die Schutzeinstellungen Ihrer Kubernetes-Workloads verwalten.


NOTE: Diese Dokumentation wird als Technologievorschau bereitgestellt. Während der Vorschau wird die Kubernetes-Funktionalität für Produktionsworkloads nicht empfohlen. Mit diesem Vorschauangebot behält sich NetApp das Recht vor, Angebotsdetails, Inhalte und Zeitpläne vor der allgemeinen Verfügbarkeit zu ändern.

Sie können die folgenden Aufgaben im Zusammenhang mit der Verwaltung von Kubernetes-Workloads ausführen:
