---
settings:
  name: BlueXP backup and recovery
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  filter:
    label: Cloud-Provider
    default: Alle Cloud-Provider
    options:
    - name: Amazon Web Services
      alias: AWS
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azure
      id: azure
  langs: de-de,us-en,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: BlueXP Backup- und Recovery-Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
    - title: Bekannte Einschränkungen für Microsoft SQL Server-Workloads
      url: "/br-limitations.html"
    - title: Bekannte Einschränkungen für ONTAP Volumes Workloads
      url: "/br-reference-limitations.html"
  - title: Los geht's
    entries:
    - title: Erfahren Sie mehr über BlueXP Backup und Recovery
      url: "/concept-backup-to-cloud.html"
    - title: Voraussetzungen für BlueXP backup and recovery
      url: "/concept-start-prereq.html"
    - title: Lizenzierung für Backup und Recovery von BlueXP einrichten
      url: "/br-start-licensing.html"
    - title: Richten Sie Sicherungsziele ein, bevor Sie BlueXP backup and recovery
        verwenden
      url: "/br-start-setup.html"
    - title: Melden Sie sich bei BlueXP backup and recovery an
      url: "/br-start-login.html"
    - title: Ermitteln von Sicherungszielen
      url: "/br-start-discover-backup-targets.html"
    - title: Wechseln Sie zu verschiedenen BlueXP backup and recovery -Workloads
      url: "/br-start-switch-ui.html"
    - title: Konfigurieren der allgemeinen Einstellungen für BlueXP backup and recovery
      url: "/br-start-configure.html"
  - title: Verwenden Sie BlueXP backup and recovery
    entries:
    - title: Anzeigen des Schutzstatus im Dashboard
      url: "/br-use-dashboard.html"
    - title: Erstellen Sie Richtlinien zur Steuerung von Backups und Wiederherstellungen
      url: "/br-use-policies-create.html"
    - title: Schützen Sie ONTAP Volume-Workloads
      entries:
      - title: Übersicht über Protect ONTAP Volume-Workloads
        url: "/prev-ontap-protect-overview.html"
      - title: Planen Sie Ihren Schutz für ONTAP -Volumes
        url: "/prev-ontap-protect-journey.html"
      - title: Management von Richtlinien für ONTAP Volumes
        url: "/prev-ontap-policy-manage.html"
      - title: Backup-to-Object-Richtlinienoptionen für ONTAP Volumes
        url: "/prev-ontap-policy-object-options.html"
      - title: Verwalten der erweiterten Einstellungsoptionen für die Backup-to-Object-Richtlinie
        url: "/prev-ontap-policy-object-advanced-settings.html"
      - title: Cloud Volumes ONTAP in Amazon S3 sichern
        url: "/prev-ontap-backup-cvo-aws.html"
      - title: Backup von Cloud Volumes ONTAP in Azure Blob
        url: "/prev-ontap-backup-cvo-azure.html"
      - title: Backup von Cloud Volumes ONTAP in der Google Cloud
        url: "/prev-ontap-backup-cvo-gcp.html"
      - title: Backup von On-Premises-ONTAP in Amazon S3
        url: "/prev-ontap-backup-onprem-aws.html"
      - title: Backup von On-Premises-ONTAP zu Azure Blob
        url: "/prev-ontap-backup-onprem-azure.html"
      - title: Sichern Sie Ihre lokale ONTAP in der Google Cloud
        url: "/prev-ontap-backup-onprem-gcp.html"
      - title: Sichern Sie On-Premises-ONTAP auf ONTAP S3
        url: "/prev-ontap-backup-onprem-ontaps3.html"
      - title: Sichern Sie Ihre lokale ONTAP auf StorageGRID
        url: "/prev-ontap-backup-onprem-storagegrid.html"
      - title: Migrieren Sie Volumes mit SnapMirror zur Cloud-Neusynchronisierung
        url: "/prev-ontap-migrate-resync.html"
      - title: ONTAP-Backups managen
        url: "/prev-ontap-backup-manage.html"
      - title: Restore aus ONTAP-Backups
        url: "/prev-ontap-restore.html"
    - title: Schützen Sie Microsoft SQL Server-Workloads (Vorschau)
      entries:
      - title: Übersicht zum Schützen von Microsoft SQL Server-Workloads
        url: "/br-use-mssql-protect-overview.html"
      - title: Konfigurieren Sie zusätzliche Elemente beim Importieren aus SnapCenter
        url: "/concept-start-prereq-snapcenter-import.html"
      - title: Entdecken Sie Microsoft SQL Server-Workloads
        url: "/br-start-discover.html"
      - title: Sichern Sie Microsoft SQL Server-Workloads
        url: "/br-use-mssql-backup.html"
      - title: Wiederherstellen von Microsoft SQL Server-Workloads
        url: "/br-use-mssql-restore.html"
      - title: Klonen von Microsoft SQL Server-Workloads
        url: "/br-use-mssql-clone.html"
      - title: Verwalten des Microsoft SQL Server-Inventars
        url: "/br-use-manage-inventory.html"
      - title: Verwalten von Microsoft SQL Server-Snapshots
        url: "/br-use-manage-snapshots.html"
      - title: Erstellen von Microsoft SQL Server-Berichten
        url: "/br-use-reports.html"
    - title: Schützen der Workloads virtueller Maschinen
      entries:
      - title: Übersicht über den Schutz virtueller Maschinen-Workloads
        url: "/prev-vmware-protect-overview.html"
      - title: Voraussetzungen für den Schutz der Workloads virtueller Maschinen
        url: "/prev-vmware-prereqs.html"
      - title: Registrieren Sie das SnapCenter Plug-in für VMware vSphere Host
        url: "/prev-vmware-register-snapcenter.html"
      - title: Erstellen einer Richtlinie zum Sichern von Daten virtueller Maschinen
        url: "/prev-vmware-policy-create.html"
      - title: Erstellen Sie Backups von Datastores in Amazon Web Services
        url: "/prev-vmware-backup-aws.html"
      - title: Sichern Sie Datastores in Microsoft Azure
        url: "/prev-vmware-backup-azure.html"
      - title: Erstellen Sie Backups von Datastores auf Google Cloud Platform
        url: "/prev-vmware-backup-gcp.html"
      - title: Sichern Sie Datenspeicher in StorageGRID
        url: "/prev-vmware-backup-storagegrid.html"
      - title: Managen Sie die Sicherung von Data Stores und Virtual Machines
        url: "/prev-vmware-manage.html"
      - title: Wiederherstellen von Daten und Datenspeichern virtueller Maschinen
        url: "/prev-vmware-restore.html"
    - title: Schützen Sie Kubernetes-Workloads (Vorschau)
      entries:
      - title: Übersicht zum Schützen von Kubernetes-Workloads
        url: "/br-use-kubernetes-protect-overview.html"
      - title: Entdecken Sie Kubernetes-Workloads
        url: "/br-start-discover-kubernetes.html"
      - title: Kubernetes-Anwendungen hinzufügen und schützen
        url: "/br-use-protect-kubernetes-applications.html"
      - title: Wiederherstellen von Kubernetes-Anwendungen
        url: "/br-use-restore-kubernetes-applications.html"
      - title: Managen Sie Kubernetes-Cluster
        url: "/br-use-manage-kubernetes-clusters.html"
      - title: Verwalten von Kubernetes-Anwendungen
        url: "/br-use-manage-kubernetes-applications.html"
      - title: Verwalten von Ausführungs-Hook-Vorlagen für Kubernetes-Workloads
        url: "/br-use-manage-execution-hook-templates.html"
    - title: Überwachen von Jobs
      url: "/br-use-monitor-tasks.html"
    - title: BlueXP Backup und Recovery neu starten
      url: "/reference-restart-backup.html"
  - title: Mit DER REST-API automatisieren
    url: "/br-api-backup-restore.html"
  - title: Referenz
    entries:
    - title: Richtlinien in SnapCenter im Vergleich zu BlueXP backup and recovery
      url: "/reference-policy-differences-snapcenter.html"
    - title: Rollen und Berechtigungen für BlueXP backup and recovery
      url: "/reference-roles.html"
    - title: Unterstützte AWS Archiv-Storage Tiers
      url: "/prev-reference-aws-archive-storage-tiers.html"
    - title: Unterstützte Azure-Archivspeicherebenen
      url: "/prev-reference-azure-archive-storage-tiers.html"
    - title: Unterstützte Google Cloud-Archivspeicherebenen
      url: "/prev-reference-gcp-archive-storage-tiers.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
