---
settings:
  name: BlueXP backup and recovery
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  filter:
    label: Cloud-Provider
    default: Alle Cloud-Provider
    options:
    - name: Amazon Web Services
      alias: AWS
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azure
      id: azure
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: BlueXP Backup- und Recovery-Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
    - title: Bekannte Einschränkungen
      url: "/reference-limitations.html"
  - title: Los geht's
    entries:
    - title: Erfahren Sie mehr über BlueXP Backup und Recovery
      url: "/concept-backup-to-cloud.html"
    - title: Lizenzierung einrichten
      url: "/task-licensing-cloud-backup.html"
  - title: Überwachen Sie die Datensicherung
    entries:
    - title: Berichte zur Datensicherung
      url: "/task-report-inventory.html"
    - title: Überwachen des Status von Backup- und Wiederherstellungsjobs
      url: "/task-monitor-backup-jobs.html"
  - title: Backup und Restore von ONTAP Daten
    entries:
    - title: Sichern von ONTAP Volume-Daten
      url: "/concept-ontap-backup-to-cloud.html"
    - title: Planen Sie Ihren Weg zum Schutz
      url: "/concept-protection-journey.html"
    - title: Management von Richtlinien für ONTAP Volumes
      url: "/task-create-policies-ontap.html"
    - title: Richtlinienoptionen für das Backup an ein Objekt
      url: "/concept-cloud-backup-policies.html"
    - title: Verwalten Sie die Backup-to-Object-Optionen unter Erweiterte Einstellungen
      url: "/task-manage-backup-settings-ontap.html"
    - title: Cloud Volumes ONTAP in Amazon S3 sichern
      flavor: aws
      url: "/task-backup-to-s3.html"
    - title: Backup von Cloud Volumes ONTAP in Azure Blob
      flavor: azure
      url: "/task-backup-to-azure.html"
    - title: Backup von Cloud Volumes ONTAP in der Google Cloud
      flavor: gcp
      url: "/task-backup-to-gcp.html"
    - title: Backup von On-Premises-ONTAP in Amazon S3
      flavor: aws
      url: "/task-backup-onprem-to-aws.html"
    - title: Backup von On-Premises-ONTAP zu Azure Blob
      flavor: azure
      url: "/task-backup-onprem-to-azure.html"
    - title: Sichern Sie Ihre lokale ONTAP in der Google Cloud
      flavor: gcp
      url: "/task-backup-onprem-to-gcp.html"
    - title: Sichern Sie On-Premises-ONTAP auf ONTAP S3
      url: "/task-backup-onprem-to-ontap-s3.html"
    - title: Sichern Sie Ihre lokale ONTAP auf StorageGRID
      url: "/task-backup-onprem-private-cloud.html"
    - title: ONTAP-Backups managen
      url: "/task-manage-backups-ontap.html"
    - title: Restore aus ONTAP-Backups
      url: "/task-restore-backups-ontap.html"
  - title: Backup und Restore von On-Premises-Applikationsdaten
    entries:
    - title: Sichern Sie Ihre lokalen Applikationsdaten
      url: "/concept-protect-app-data-to-cloud.html"
    - title: Registrieren Sie den SnapCenter-Server
      url: "/task-register-snapcenter-server.html"
    - title: Erstellen einer Richtlinie für das Backup von Applikationen
      url: "/task-create-policies-apps.html"
    - title: Sichern Sie On-Premises-Applikationsdaten in Amazon Web Services
      flavor: aws
      url: "/task-backup-app-data-to-aws.html"
    - title: Sichern Sie On-Premises-Applikationsdaten in Microsoft Azure
      flavor: azure
      url: "/task-backup-app-data-to-azure.html"
    - title: On-Premises-Applikationsdaten in Google Cloud sichern
      flavor: gcp
      url: "/task-backup-app-data-to-gcp.html"
    - title: Sichern Sie On-Premises-Applikationsdaten in StorageGRID
      url: "/task-backup-app-data-to-storagegrid.html"
    - title: Management der Sicherung von Applikationen
      url: "/task-manage-app-backups.html"
    - title: Wiederherstellung von lokalen Applikationsdaten
      entries:
      - title: Oracle Datenbank wiederherstellen
        url: "/task-restore-oracle-data.html"
      - title: SQL Server Datenbank wiederherstellen
        url: "/task-restore-sql-data.html"
      - title: Wiederherstellung der SAP HANA Datenbank
        url: "/task-restore-hana-backup.html"
      - title: Stellen Sie MongoDB-, MySQL- und PostgreSQL-Datenbanken wieder her
        url: "/task-restore-customplugin-backup.html"
  - title: Daten von Virtual Machines sichern und wiederherstellen
    entries:
    - title: Sichern Sie Ihre Daten von Virtual Machines
      url: "/concept-protect-vm-data.html"
    - title: Registrieren Sie das SnapCenter Plug-in für VMware vSphere Host
      url: "/task-register-snapCenter-plug-in-for-vmware-vsphere.html"
    - title: Erstellen Sie eine Richtlinie zum Backup von Datastores
      url: "/task-create-policies-vms.html"
    - title: Erstellen Sie Backups von Datastores in Amazon Web Services
      flavor: aws
      url: "/task-backup-vm-data-to-aws.html"
    - title: Sichern Sie Datastores in Microsoft Azure
      flavor: azure
      url: "/task-backup-vm-data-to-azure.html"
    - title: Erstellen Sie Backups von Datastores auf Google Cloud Platform
      flavor: gcp
      url: "/task-backup-vm-data-to-gcp.html"
    - title: Sichern Sie Datenspeicher in StorageGRID
      url: "/task-backup-vm-data-to-storagegrid.html"
    - title: Managen Sie die Sicherung von Data Stores und Virtual Machines
      url: "/task-manage-vm-data-in-cloud.html"
    - title: Stellen Sie die Daten von Virtual Machines wieder her
      url: "/task-restore-vm-data.html"
  - title: Mit DER REST-API automatisieren
    url: "/api-backup-restore.html"
  - title: Referenz
    entries:
    - title: Unterstützte AWS Archiv-Storage Tiers
      url: "/reference-aws-backup-tiers.html"
    - title: Unterstützte Azure-Archiv-Zugriffsebenen
      url: "/reference-azure-backup-tiers.html"
    - title: Unterstützte Google-Archiv-Storage Tiers
      url: "/reference-google-backup-tiers.html"
    - title: Backup für Multi-Account-Zugriff in Azure konfigurieren
      flavor: azure
      url: "/reference-backup-multi-account-azure.html"
    - title: Stellen Sie BlueXP Backup- und Recovery-Datenbanken an einem dunklen
        Standort wieder her
      url: "/reference-backup-cbs-db-in-dark-site.html"
    - title: BlueXP Backup und Recovery neu starten
      url: "/reference-restart-backup.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/task-support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
