---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, backup, restore, backup and recovery 
summary: Bekannte Einschränkungen identifizieren Funktionen, die von dieser Version des Produkts nicht unterstützt werden oder nicht korrekt mit ihr zusammenarbeiten. Lesen Sie diese Einschränkungen sorgfältig durch. 
---
= Bekannte Einschränkungen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bekannte Einschränkungen identifizieren Funktionen, die von dieser Version des Produkts nicht unterstützt werden oder nicht korrekt mit ihr zusammenarbeiten. Lesen Sie diese Einschränkungen sorgfältig durch.



== Einschränkungen bei Backup und Restore für ONTAP Volumes



=== Einschränkungen bei der Replizierung

* Sie können jeweils nur ein FlexGroup-Volume für die Replikation auswählen. Sie müssen Backups für jedes FlexGroup Volume separat aktivieren.
+
Es gibt keine Beschränkung für FlexVol Volumes: Sie können alle FlexVol Volumes in Ihrer Arbeitsumgebung auswählen und dieselben Backup-Richtlinien zuweisen.

* Die folgenden Funktionen werden in unterstützt https://docs.netapp.com/us-en/bluexp-replication/index.html["BlueXP Replizierungsservice"], Aber nicht, wenn Sie die Replizierungsfunktion von BlueXP Backup und Recovery nutzen:
+
** Es wird keine Kaskadenkonfiguration unterstützt, bei der die Replikation von Volume A auf Volume B und von Volume B auf Volume C erfolgt Die Unterstützung umfasst die Replikation von Volume A auf Volume B.
** Es wird keine Unterstützung für die Replizierung von Daten zu und von FSX for ONTAP Systemen geleistet.
** Es wird nicht unterstützt, eine einmalige Replikation eines Volumes zu erstellen.


* Wenn die ONTAP-Version auf dem Cloud Volumes ONTAP-Zielsystem 9.8, 9.9 oder 9.11 ist, sind bei der Erstellung von Replikationen aus lokalen ONTAP-Systemen nur Richtlinien für Spiegelungen zulässig.




=== Einschränkungen bei Backups auf Objekte

* Wenn Sie eine Backup-Richtlinie erstellen oder bearbeiten, wenn dieser Richtlinie keine Volumes zugewiesen sind, kann die Anzahl der behielten Backups maximal 1018 sein. Nachdem Sie der Richtlinie Volumes zugewiesen haben, können Sie die Richtlinie für die Erstellung von bis zu 4000 Backups bearbeiten.
* Bei der Sicherung von Datensicherungs-Volumes (DP):
+
** Beziehungen zu den SnapMirror-Labels `app_consistent` Und `all_source_snapshot` Wird nicht in der Cloud gesichert werden.
** Wenn Sie lokale Kopien der Snapshots auf dem SnapMirror Ziel-Volume erstellen (unabhängig von den verwendeten SnapMirror Bezeichnungen), werden diese Snapshots nicht als Backups in die Cloud verschoben. Sie müssen derzeit eine Snapshot-Richtlinie mit den gewünschten Labels auf dem DP-Quell-Volume erstellen, damit Backups durch BlueXP Backup und Recovery erstellt werden können.


* FlexGroup Volume-Backups können nicht in Archiv-Storage verschoben werden.
* FlexGroup Volume-Backups können DataLock und Ransomware-Schutz verwenden, wenn auf dem Cluster ONTAP 9.13.1 oder höher ausgeführt wird.
* SVM-DR-Volume-Backup wird unter den folgenden Einschränkungen unterstützt:
+
** Backups werden nur von der sekundären ONTAP unterstützt.
** Die auf das Volume angewendete Snapshot-Richtlinie muss eine der durch BlueXP Backup- und Recovery-Richtlinien sein, einschließlich täglich, wöchentlich, monatlich usw. Die standardmäßige „SM_created“-Richtlinie (verwendet für *Mirror All Snapshots*) wird nicht erkannt und das DP-Volume wird nicht in der Liste der Volumes angezeigt, die gesichert werden können.




* MetroCluster-Unterstützung:
+
** Wenn Sie ONTAP 9.12.1 GA oder höher verwenden, wird das Backup unterstützt, wenn eine Verbindung zum primären System hergestellt wird. Die gesamte Backup-Konfiguration wird auf das sekundäre System übertragen, sodass Backups in die Cloud nach dem Switchover automatisch fortgesetzt werden. Sie müssen keine Sicherungskopie auf dem sekundären System einrichten (tatsächlich sind Sie darauf beschränkt).
** Bei Verwendung von ONTAP 9.12.0 und älteren Versionen wird ein Backup nur vom sekundären ONTAP System unterstützt.
** Backups von FlexGroup-Volumes werden derzeit nicht unterstützt.


* Ad-hoc-Volume-Backup mit der *Backup Now*-Taste wird auf Datensicherungs-Volumes nicht unterstützt.
* SM-BC-Konfigurationen werden nicht unterstützt.
* ONTAP unterstützt kein Fan-out von SnapMirror Beziehungen von einem einzelnen Volume zu mehreren Objektspeichern. Daher wird diese Konfiguration von BlueXP Backup und Recovery nicht unterstützt.
* DER WORM-/Compliance-Modus für einen Objektspeicher wird derzeit auf Amazon S3, Azure und StorageGRID unterstützt. Dies ist die sogenannte DataLock-Funktion, die über die Backup- und Recovery-Einstellungen von BlueXP gemanagt werden muss, nicht über die Cloud-Provider-Schnittstelle.




=== Restore-Einschränkungen

Diese Einschränkungen gelten sowohl für die Such- und Wiederherstellungsmethoden als auch für die Such- und Wiederherstellungsmethoden für die Wiederherstellung von Dateien und Ordnern, sofern nicht ausdrücklich genannt.

* Browse & Restore kann bis zu 100 einzelne Dateien gleichzeitig wiederherstellen.
* Search & Restore kann 1 Datei gleichzeitig wiederherstellen.
* Wenn Sie ONTAP 9.13.0 oder höher verwenden, können Sie einen Ordner mit allen darin enthaltenen Dateien und Unterordnern durchsuchen und wiederherstellen und suchen und wiederherstellen.
+
Bei Verwendung einer Version von ONTAP größer als 9.11.1, aber vor 9.13.0, kann der Wiederherstellungsvorgang nur den ausgewählten Ordner und die Dateien in diesem Ordner wiederherstellen - keine Unterordner oder Dateien in Unterordnern werden wiederhergestellt.

+
Wenn Sie eine Version von ONTAP vor 9.11.1 verwenden, wird die Wiederherstellung von Ordnern nicht unterstützt.

* Die Wiederherstellung von Verzeichnissen/Ordnern wird nur bei Daten unterstützt, die sich im Archiv-Storage befinden, wenn auf dem Cluster ONTAP 9.13.1 und höher ausgeführt wird.
* Die Wiederherstellung von Verzeichnissen/Ordnern wird nur für Daten unterstützt, die mit DataLock geschützt sind, wenn auf dem Cluster ONTAP 9.13.1 und höher ausgeführt wird.
* Die Wiederherstellung von Verzeichnissen/Ordnern wird derzeit nicht von FlexGroup-Volume-Backups unterstützt.
* Die Wiederherstellung von Verzeichnissen/Ordnern wird derzeit nicht von Replikationen und/oder lokalen Snapshots unterstützt.
* Die Wiederherstellung von FlexGroup Volumes auf FlexVol Volumes oder FlexVol Volumes auf FlexGroup Volumes wird nicht unterstützt.
* Die wiederherzustellende Datei muss die gleiche Sprache verwenden wie die Sprache auf dem Zielvolume. Wenn die Sprachen nicht identisch sind, wird eine Fehlermeldung angezeigt.
* Die Priorität _High_ restore wird beim Wiederherstellen von Daten aus dem Azure Archiv-Storage auf StorageGRID-Systeme nicht unterstützt.
* Einschränkungen bei der schnellen Wiederherstellung:
+
** Der Zielspeicherort muss ein Cloud Volumes ONTAP-System mit ONTAP 9.13.0 oder höher sein.
** Es wird nicht unterstützt, wenn sich Backups im archivierten Speicher befinden.
** FlexGroup Volumes werden nur unterstützt, wenn auf dem Quellsystem, auf dem das Cloud-Backup erstellt wurde, ONTAP 9.12.1 oder höher ausgeführt wurde.
** SnapLock Volumes werden nur unterstützt, wenn auf dem Quellsystem, auf dem das Cloud-Backup erstellt wurde, ONTAP 9.11.0 oder höher ausgeführt wurde.



