---
sidebar: sidebar 
permalink: reference-configure-fsx-for-ontap.html 
keywords: Cloud Manager, FSx for ONTAP, working environment, Connector, BlueXP 
summary: Erstellen Sie die FSX für ONTAP-Arbeitsumgebung und den Connector 
---
= Konfigurieren Sie FSX für ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mit BlueXP sollten Sie eine Arbeitsumgebung FSX for ONTAP erstellen, um Volumes und zusätzliche Datenservices hinzuzufügen und zu managen. Sie sollten auch einen Connector in AWS erstellen, mit dem BlueXP Ressourcen und Prozesse in der Public Cloud-Umgebung des Kunden managen kann.



== Erstellung von FSX für ONTAP-Arbeitsumgebung

Sie sollten die FSX für ONTAP Arbeitsumgebungen erstellen, in denen Ihre Datenbanken gehostet werden. Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/task-getting-started-fsx.html["Erste Schritte mit Amazon FSX für ONTAP"] Und link:https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-creating-fsx-working-environment.html["Erstellung und Management einer Amazon FSX für ONTAP Arbeitsumgebung"].

Die Arbeitsumgebung FSX for ONTAP lässt sich entweder mit BlueXP oder AWS erstellen. Falls Sie mit AWS erstellt haben, sollten Sie die FSX für ONTAP Systeme in BlueXP entdecken.



== Einen Konnektor erstellen

Ein Kontoadministrator muss einen Connector in AWS erstellen, mit dem BlueXP Ressourcen und Prozesse in der Public Cloud-Umgebung des Kunden managen kann.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-aws.html["Erstellen eines Connectors in AWS aus BlueXP"].

* Sie sollten denselben Konnektor verwenden, um sowohl FSX für ONTAP Arbeitsumgebungen als auch Datenbanken zu verwalten.
* Wenn die Arbeitsumgebung FSX for ONTAP und Datenbanken in derselben Virtual Private Cloud (VPC) liegen, können Sie den Connector in derselben VPC implementieren.
* Wenn Sie die FSX for ONTAP Arbeitsumgebung und Datenbanken in verschiedenen VPCs haben:
+
** Wenn Sie NAS (NFS) Workloads auf FSX für ONTAP konfiguriert haben, können Sie den Connector auf einem der vPCs erstellen.
** Wenn Sie nur SAN-Workloads konfiguriert haben und keine NAS (NFS)-Workloads verwenden möchten, sollten Sie den Connector in der VPC erstellen, wo das FSX für ONTAP-System erstellt wird.
+

NOTE: Für die Nutzung von NAS-Workloads (NFS) sollten Sie über ein Transit-Gateway zwischen der Datenbank VPC und Amazon VPC verfügen. Auf die NFS-IP-Adresse, die eine unverankerte IP-Adresse ist, kann von einer anderen VPC nur über das Transit-Gateway zugegriffen werden. Wir können nicht auf die Floating IP-Adressen zugreifen, indem wir die VPCs Peering.





Klicken Sie nach dem Erstellen des Connectors auf *Speicher* > *Leinwand* > *Meine Arbeitsumgebung* > *Arbeitsumgebung hinzufügen* und folgen Sie den Anweisungen, um die Arbeitsumgebung hinzuzufügen. Stellen Sie sicher, dass eine Verbindung zwischen dem Connector und den Oracle-Datenbank-Hosts und der FSX-Arbeitsumgebung besteht. Der Connector sollte in der Lage sein, eine Verbindung zur Cluster-Management-IP-Adresse der FSX Arbeitsumgebung herzustellen.

* Fügen Sie die Arbeitsumgebung hinzu, indem Sie auf *Speicher* > *Leinwand* > *Meine Arbeitsumgebung* > *Arbeitsumgebung hinzufügen* klicken.
+
Stellen Sie sicher, dass eine Verbindung zwischen dem Connector und den Datenbank-Hosts und der Arbeitsumgebung von FSX for ONTAP besteht. Der Connector sollte eine Verbindung zur Cluster-Management-IP-Adresse der Arbeitsumgebung FSX für ONTAP herstellen.

* Kopieren Sie die Connector-ID, indem Sie auf *Connector > Connectors verwalten* klicken und den Connector-Namen auswählen.

