---
sidebar: sidebar 
permalink: reference-backup-cbs-db-in-dark-site.html 
keywords: backup database, recover database 
summary: Wenn Sie BlueXP Backup und Recovery an einer Site ohne Internetzugang nutzen, bekannt als „privater Modus“, werden die Backup- und Recovery-Konfigurationsdaten von BlueXP auf den StorageGRID oder ONTAP S3 Bucket gesichert, auf dem die Backups gespeichert werden. Wenn Sie in Zukunft Probleme mit dem BlueXP Connector-Host-System haben, können Sie einen neuen Connector implementieren und die kritischen BlueXP Backup- und Recovery-Daten wiederherstellen. 
---
= Stellen Sie BlueXP Backup- und Recovery-Daten an einem dunklen Standort wieder her
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie BlueXP Backup und Recovery an einem Standort ohne Internetzugang nutzen, den sogenannten _Private Mode_, werden die Backup- und Recovery-Konfigurationsdaten von BlueXP auf den StorageGRID oder ONTAP S3 Bucket gesichert, auf dem die Backups gespeichert werden. Wenn Sie in Zukunft Probleme mit dem BlueXP Connector-Host-System haben, können Sie einen neuen Connector implementieren und die kritischen BlueXP Backup- und Recovery-Daten wiederherstellen.

Beachten Sie, dass wenn Sie BlueXP Backup und Recovery in einer SaaS-Umgebung nutzen, bei der BlueXP Connector bei Ihrem Cloud-Provider oder in Ihrem eigenen Host-System mit Internetzugang implementiert wird, alle wichtigen BlueXP Backup- und Recovery-Konfigurationsdaten gesichert und in der Cloud gesichert werden. Wenn Sie ein Problem mit dem Connector haben, erstellen Sie einfach einen neuen Connector und fügen Sie Ihre Arbeitsumgebungen hinzu. Die Sicherungsdetails werden automatisch wiederhergestellt.

Es gibt 2 Arten von Daten, die gesichert werden:

* BlueXP Backup- und Recovery-Datenbank – enthält eine Liste aller Volumes, Backup-Dateien, Backup-Richtlinien und Konfigurationsinformationen.
* Indizierte Katalogdateien – enthält detaillierte Indizes, die für die Such- und Wiederherstellungsfunktion verwendet werden, sodass Ihre Suchvorgänge sehr schnell und effizient bei der Suche nach Volume-Daten, die Sie wiederherstellen möchten, durchgeführt werden.


Diese Daten werden einmal am Tag um Mitternacht gesichert und maximal 7 Kopien jeder Datei werden aufbewahrt. Wenn der Connector mehrere lokale ONTAP-Arbeitsumgebungen managt, befinden sich die Backup- und Recovery-Dateien von BlueXP im Bucket der Arbeitsumgebung, die zuerst aktiviert wurde.


TIP: In der BlueXP Backup- und Recovery-Datenbank oder den indizierten Katalogdateien werden keine Volume-Daten jemals enthalten sein.



== Wiederherstellung von BlueXP Backup- und Recovery-Daten in einem neuen Connector

Wenn Ihr lokaler Connector bei einem schwerwiegenden Ausfall auftritt, müssen Sie einen neuen Connector installieren und anschließend die BlueXP Backup- und Recovery-Daten im neuen Connector wiederherstellen.

Es gibt 4 Aufgaben, die Sie durchführen müssen, um den Betriebszustand Ihres BlueXP Backup- und Recovery-Systems wiederherzustellen:

* Installieren Sie einen neuen BlueXP Connector
* Wiederherstellung der BlueXP Backup- und Recovery-Datenbank
* Stellen Sie die indizierten Katalogdateien wieder her
* Alle On-Prem-ONTAP-Systeme und StorageGRID-Systeme finden Sie in der BlueXP-Benutzeroberfläche wieder


Sobald Sie überprüfen, ob Ihr System wieder in einem Arbeitsauftrag ist, empfehlen wir Ihnen, neue Sicherungsdateien zu erstellen.

.Was Sie benötigen
Sie müssen über den StorageGRID oder ONTAP S3 Bucket auf die neuesten Datenbank- und Index-Backups zugreifen, in denen Ihre Backup-Dateien gespeichert werden:

* BlueXP Backup und Recovery der MySQL-Datenbankdatei
+
Diese Datei befindet sich am folgenden Speicherort im Bucket `netapp-backup-<GUID>/mysql_backup/`, Und es ist benannt `CBS_DB_Backup_<day>_<month>_<year>.sql`.

* ZIP-Datei für die Sicherung des indizierten Katalogs
+
Diese Datei befindet sich am folgenden Speicherort im Bucket `netapp-backup-<GUID>/catalog_backup/`, Und es ist benannt `Indexed_Catalog_DB_Backup_<db_name>_<day>_<month>_<year>.zip`.





=== Installieren Sie einen neuen Konnektor auf einem neuen lokalen Linux-Host

Wenn Sie einen neuen BlueXP Connector installieren, stellen Sie sicher, dass Sie die gleiche Version von Software herunterladen, die Sie auf dem ursprünglichen Connector installiert hatten. Regelmäßige Änderungen an der BlueXP Datenbank-Struktur für Backup und Recovery führen möglicherweise dazu, dass neuere Software-Versionen mit den ursprünglichen Datenbank-Backups nicht kompatibel sind. Das können Sie https://docs.netapp.com/us-en/bluexp-setup-admin/task-managing-connectors.html#upgrade-the-connector-on-prem-without-internet-access["Aktualisieren Sie die Connector-Software auf die aktuellste Version, nachdem Sie die Backup-Datenbank wiederhergestellt haben"^].

. https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["Installieren Sie den BlueXP Connector auf einem neuen lokalen Linux-Host"^]
. Melden Sie sich mit den soeben erstellten Admin-Benutzeranmeldeinformationen bei BlueXP an.




=== Wiederherstellung der BlueXP Backup- und Recovery-Datenbank

. Kopieren Sie das MySQL-Backup vom Backup-Speicherort auf den neuen Connector-Host. Wir verwenden unten den Beispieldateinamen „CBS_DB_Backup_23_05_2023.sql“.
. Kopieren Sie das Backup mit dem folgenden Befehl in den MySQL-Docker-Container:
+
[source, cli]
----
docker cp CBS_DB_Backup_23_05_2023.sql ds_mysql_1:/.
----
. Geben Sie die MySQL-Container-Shell mithilfe des folgenden Befehls ein:
+
[source, cli]
----
docker exec -it ds_mysql_1 sh
----
. In der Container-Shell, stellen Sie die "env".
. Sie benötigen das MySQL DB Passwort, kopieren Sie also den Wert des Schlüssels "MYSQL_ROOT_PASSWORD".
. Stellen Sie die BlueXP Backup und Recovery MySQL DB mit folgendem Befehl wieder her:
+
[source, cli]
----
mysql -u root -p cloud_backup < CBS_DB_Backup_23_05_2023.sql
----
. Überprüfen Sie mit den folgenden SQL-Befehlen, ob die BlueXP Backup- und Recovery-MySQL DB korrekt wiederhergestellt wurde:
+
[source, cli]
----
mysql -u root -p cloud_backup
----
+
Geben Sie das Passwort ein.

+
[source, cli]
----
mysql> show tables;
mysql> select * from volume;
----
+
Überprüfen Sie, ob die angezeigten Volumen dieselben sind wie die in Ihrer ursprünglichen Umgebung.





=== Stellen Sie die indizierten Katalogdateien wieder her

. Kopieren Sie die ZIP-Datei mit dem indizierten Katalog (wir verwenden den Beispieldateinamen „indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip“) vom Sicherungsverzeichnis auf den neuen Connector-Host im Ordner „/opt/Application/netapp/cbs“.
. Entpacken Sie die Datei „indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip“ mit folgendem Befehl:
+
[source, cli]
----
unzip Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip -d catalogdb1
----
. Führen Sie den Befehl *ls* aus, um sicherzustellen, dass der Ordner "catalogdb1" mit den Unterordnern "changes" und "catalogs" darunter angelegt wurde.




=== Erkennen Sie Ihre ONTAP Cluster und StorageGRID Systeme

. https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html#discover-clusters-using-a-connector["Hier finden Sie alle On-Premises-ONTAP-Arbeitsumgebungen"^] Die in Ihrer vorherigen Umgebung verfügbar waren. Dazu gehört auch das ONTAP-System, das Sie als S3-Server genutzt haben.
. https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["Erkennen Sie Ihre StorageGRID Systeme"^].




=== Richten Sie die Details zur StorageGRID Umgebung ein

Fügen Sie die Details des StorageGRID-Systems zu Ihren ONTAP-Arbeitsumgebungen hinzu, da diese auf dem ursprünglichen Konnektor-Setup mithilfe der eingerichtet wurden https://docs.netapp.com/us-en/bluexp-automation/index.html["BlueXP APIs"^].

Sie müssen diese Schritte für jedes ONTAP System durchführen, das Daten in StorageGRID sichert.

. Extrahieren Sie das Autorisierungs-Token mithilfe der folgenden oauth/Token-API.
+
[source, http]
----
curl 'http://10.193.192.202/oauth/token' -X POST -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:100101 Firefox/108.0' -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/json' -d '{"username":admin@netapp.com,"password":"Netapp@123","grant_type":"password"}
> '
----
+
Diese API gibt eine Antwort wie die folgende zurück. Sie können das Autorisierungs-Token wie unten gezeigt abrufen.

+
[source, text]
----
{"expires_in":21600,"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzM2MDIzLCJleHAiOjE2NzI3NTc2MjMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9CJtRpRDY23PokyLg1if67bmgnMcYxdCvBOY-ZUYWzhrWbbY_hqUH4T-114v_pNDsPyNDyWqHaKizThdjjHYHxm56vTz_Vdn4NqjaBDPwN9KAnC6Z88WA1cJ4WRQqj5ykODNDmrv5At_f9HHp0-xVMyHqywZ4nNFalMvAh4xESc5jfoKOZc-IOQdWm4F4LHpMzs4qFzCYthTuSKLYtqSTUrZB81-o-ipvrOqSo1iwIeHXZJJV-UsWun9daNgiYd_wX-4WWJViGEnDzzwOKfUoUoe1Fg3ch--7JFkFl-rrXDOjk1sUMumN3WHV9usp1PgBE5HAcJPrEBm0ValSZcUbiA"}
----
. Extrahieren Sie die ID der Arbeitsumgebung und die X-Agent-ID mithilfe der Tenancy/External/Resource API.
+
[source, http]
----
curl -X GET http://10.193.192.202/tenancy/external/resource?account=account-DARKSITE1 -H 'accept: application/json' -H 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw'
----
+
Diese API gibt eine Antwort wie die folgende zurück. Der Wert unter der "resourceIdentifier" bezeichnet die _WorkingEnvironment ID_ und der Wert unter "AGENTID" bezeichnet _x-Agent-id_.

. Aktualisieren Sie die BlueXP Backup- und Recovery-Datenbank mit den Details des StorageGRID Systems, das den Arbeitsumgebungen zugeordnet ist. Stellen Sie sicher, dass Sie den vollständig qualifizierten Domänennamen der StorageGRID sowie den Zugriffsschlüssel und den Speicherschlüssel wie unten dargestellt eingeben:
+
[source, http]
----
curl -X POST 'http://10.193.192.202/account/account-DARKSITE1/providers/cloudmanager_cbs/api/v1/sg/credentials/working-environment/OnPremWorkingEnvironment-pMtZND0M' \
> --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw' \
> --header 'x-agent-id: vB_1xShPpBtUosjD7wfBlLIhqDgIPA0wclients' \
> -d '
> { "storage-server" : "sr630ip15.rtp.eng.netapp.com:10443", "access-key": "2ZMYOAVAS5E70MCNH9", "secret-password": "uk/6ikd4LjlXQOFnzSzP/T0zR4ZQlG0w1xgWsB" }'
----




=== Überprüfen Sie die Backup- und Recovery-Einstellungen von BlueXP

. Wählen Sie jede ONTAP Arbeitsumgebung aus und klicken Sie auf *Backups anzeigen* neben dem Backup- und Recovery-Service im rechten Fenster.
+
Sie sollten in der Lage sein alle Backups zu sehen, die für Ihre Volumes erstellt wurden.

. Klicken Sie im Dashboard wiederherstellen im Abschnitt Suchen & Wiederherstellen auf *Indexing-Einstellungen*.
+
Stellen Sie sicher, dass die Arbeitsumgebungen, in denen die Indexierung bereits aktiviert war, zuvor aktiviert bleiben.

. Führen Sie auf der Seite Suchen & Wiederherstellen einige Katalogsuchen aus, um zu bestätigen, dass die Wiederherstellung des indizierten Katalogs erfolgreich abgeschlossen wurde.

