---
sidebar: sidebar 
permalink: reference-configure-azure-netapp-files.html 
keywords: Cloud Manager, Azure NetApp Files, working environment, Connector, BlueXP 
summary: Erstellung der Azure NetApp Files-Arbeitsumgebung und des Connectors 
---
= Konfigurieren Sie Azure NetApp Files
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mit BlueXP sollten Sie eine Azure NetApp Files Arbeitsumgebung erstellen, um Volumes und zusätzliche Datenservices hinzuzufügen und zu managen. Sie sollten auch einen Connector in Azure erstellen, mit dem BlueXP Ressourcen und Prozesse in der Public Cloud-Umgebung des Kunden managen kann.



== Azure NetApp Files Arbeitsumgebung erstellen

Sie sollten Azure NetApp Files-Arbeitsumgebungen erstellen, in denen Ihre Datenbanken gehostet werden. Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/cloud-manager-azure-netapp-files/concept-azure-netapp-files.html["Weitere Informationen zu Azure NetApp Files"] Und link:https://docs.netapp.com/us-en/cloud-manager-azure-netapp-files/task-create-working-env.html["Schaffung einer Azure NetApp Files-Arbeitsumgebung"].



== Einen Konnektor erstellen

Ein BlueXP Account-Administrator sollte einen Connector in Azure implementieren, der BlueXP ermöglicht, Ressourcen und Prozesse in der Public Cloud-Umgebung zu managen.


NOTE: Sie können die neue Connector_id nicht von der UI aktualisieren.

Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-azure.html["Erstellen Sie einen Connector in Azure von BlueXP"].

* Sie sollten denselben Konnektor verwenden, um sowohl Azure NetApp Files-Arbeitsumgebungen als auch Datenbanken zu verwalten.
* Wenn sich die Azure NetApp Files-Arbeitsumgebung und -Datenbanken im gleichen virtuellen Netzwerk (vnet) befinden, können Sie den Connector im gleichen vnet bereitstellen.
* Wenn Sie die Arbeitsumgebung von Azure NetApp Files und Datenbanken in verschiedenen VNets haben und NAS (NFS) Workloads auf Azure NetApp Files konfiguriert haben, können Sie den Connector auf einem der VNets erstellen.


Führen Sie nach dem Erstellen des Konnektors folgende Schritte aus:

* Fügen Sie die Arbeitsumgebung hinzu, indem Sie auf *Speicher* > *Leinwand* > *Meine Arbeitsumgebung* > *Arbeitsumgebung hinzufügen* klicken.
+
Stellen Sie sicher, dass eine Verbindung zwischen dem Connector und den Datenbank-Hosts und der Azure NetApp Files-Arbeitsumgebung besteht. Der Anschluss sollte mit der Azure NetApp Files-Arbeitsumgebung verbunden werden.

* Kopieren Sie die Connector-ID, indem Sie auf *Connector > Connectors verwalten* klicken und den Connector-Namen auswählen.

