---
sidebar: sidebar 
permalink: reference-configure-cloud-volumes-ontap.html 
keywords: Cloud Manager, Cloud Volumes ONTAP, working environment, Connector, BlueXP 
summary: Erstellung der Cloud Volumes ONTAP-Arbeitsumgebung und des Connectors 
---
= Konfigurieren Sie Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mit BlueXP sollten Sie eine Cloud Volumes ONTAP Arbeitsumgebung erstellen, um Volumes und zusätzliche Datenservices hinzuzufügen und zu managen. Sie sollten auch einen Connector für Ihre Cloud-Umgebung erstellen, mit dem BlueXP Ressourcen und Prozesse in der Public Cloud-Umgebung managen kann.



== Cloud Volumes ONTAP Arbeitsumgebung erstellen

Sie können vorhandene Cloud Volumes ONTAP-Systeme entdecken und zu BlueXP hinzufügen. Weitere Informationen finden Sie unter link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-adding-systems.html["Hinzufügen vorhandener Cloud Volumes ONTAP-Systeme zu BlueXP"].



== Einen Konnektor erstellen

Erste Schritte mit Cloud Volumes ONTAP für Ihre Cloud-Umgebung. Weitere Informationen finden Sie in einer der folgenden Links:

* link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-getting-started-aws.html["Schnellstart für Cloud Volumes ONTAP in AWS"]
* link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-getting-started-azure.html["Schnellstart für Cloud Volumes ONTAP in Azure"]
* link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-getting-started-gcp.html["Schnellstart für Cloud Volumes ONTAP in Google Cloud"]


Sie sollten denselben Konnektor verwenden, um sowohl Cloud Volumes ONTAP-Arbeitsumgebungen als auch Datenbanken zu verwalten.

* Wenn sich die Arbeitsumgebung von Cloud Volumes ONTAP und Datenbanken in derselben virtuellen Private Cloud (VPC) oder vnet befinden, können Sie den Connector in derselben VPC oder vnet implementieren.
* Wenn Sie die Cloud Volumes ONTAP-Arbeitsumgebung und Datenbanken in verschiedenen VPCs oder VNets haben, stellen Sie sicher, dass die VPCs oder VNets peered sind.

