---
sidebar: sidebar 
permalink: task-register-snapCenter-plug-in-for-vmware-vsphere.html 
keywords: register, registration, SnapCenter Plug-in for VMware vSphere 
summary: Registrieren Sie das SnapCenter Plug-in für den VMware vSphere Host in BlueXP. 
---
= Registrieren Sie das SnapCenter-Plug-in für den VMware vSphere-Host mit BlueXP Backup und Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie sollten das SnapCenter-Plug-in für den VMware vSphere-Host in BlueXP Backup and Recovery registrieren, damit die Datenspeicher und virtuellen Maschinen angezeigt werden. Das SnapCenter-Plug-in für den VMware vSphere-Host kann nur von einem Benutzer mit Administratorzugriff registriert werden.

.Schritte
. Klicken Sie in BlueXP UI auf *Schutz* > *Sicherung und Wiederherstellung* > *Virtuelle Maschinen*.
. Klicken Sie im Dropdown-Menü *Einstellungen* auf *SnapCenter Plug-in für VMware vSphere*.
. Klicken Sie auf *Registrieren SnapCenter Plug-in für VMware vSphere*.
. Geben Sie folgende Details an:
+
.. Geben Sie im Feld SnapCenter-Plug-in für VMware vSphere den FQDN oder die IP-Adresse des SnapCenter-Plug-ins für VMware vSphere-Hosts an.
.. Geben Sie im Feld Port die Portnummer an, auf der das SnapCenter-Plug-in für VMware vSphere-Host ausgeführt wird.
+
Sie sollten sicherstellen, dass die Kommunikation zwischen dem lokalen SnapCenter-Plug-in für VMware vSphere Host, der auf der standardmäßigen 8144-Port- und BlueXP Connector-Instanz ausgeführt wird, offen ist. Diese kann bei einem beliebigen Cloud-Provider (Amazon Web Services, Microsoft Azure, Google Cloud Platform) oder lokal ausgeführt werden.

.. Geben Sie im Feld Benutzername und Kennwort die Anmeldeinformationen des vCenter-Benutzers mit der Administratorrolle an.


. Klicken Sie Auf *Registrieren*.


*Nach Ihrer Beendigung*

Klicken Sie auf *Sicherung und Wiederherstellung* > *Virtuelle Maschinen*, um alle Datastores und virtuellen Maschinen anzuzeigen, die mit dem registrierten SnapCenter-Plug-in für VMware vSphere-Host geschützt sind.
