---
sidebar: sidebar 
permalink: task-restore-sql-data.html 
keywords: restore, Azure, Amazon Web services, Microsoft SQL Server database 
summary: Sie können eine SQL Server Datenbank aus der Cloud auf dem lokalen SnapCenter Server wiederherstellen. 
---
= SQL Server Datenbank wiederherstellen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die SQL Server Datenbank entweder am ursprünglichen Speicherort oder an einem alternativen Speicherort wiederherstellen.


NOTE: Single File Restore (SFR), Recovery von Protokoll-Backups und erneutes Seeding von Verfügbarkeitsgruppen werden nicht unterstützt.

.Schritte
. Klicken Sie in BlueXP UI auf *Schutz* > *Sicherung und Wiederherstellung* > *Anwendungen*.
. Wählen Sie im Feld *Filtern nach* den Filter *Typ* aus und wählen Sie aus dem Dropdown-Menü *SQL* aus.
. Klicken Sie auf *Details anzeigen*, um alle verfügbaren Backups anzuzeigen.
. Wählen Sie das Backup aus und klicken Sie auf *Wiederherstellen*.
. Geben Sie auf der Seite Wiederherstellungsoptionen den Speicherort an, an dem Sie die Datenbankdateien wiederherstellen möchten.
+
|===
| Sie suchen... | Tun Sie das... 


 a| 
Sie möchten den ursprünglichen Speicherort wiederherstellen
 a| 
.. Wählen Sie *auf ursprünglichen Speicherort zurücksetzen*.
.. Wenn sich der Snapshot im Archiv-Speicher befindet, wählen Sie die Priorität für die Wiederherstellung der Daten aus dem Archiv-Speicher aus.
+

NOTE: Nur wenn Sie Amazon Web Services oder Microsoft Azure als Cloud-Provider verwenden, müssen Sie die Priorität angeben.

.. Klicken Sie Auf *Weiter*.




 a| 
Sie möchten vorübergehend in einem anderen Speicher wiederherstellen und dann die wiederhergestellten Dateien an den ursprünglichen Speicherort kopieren
 a| 
.. Wählen Sie *auf ursprünglichen Speicherort zurücksetzen*.
.. Wenn sich der Snapshot im Archiv-Speicher befindet, wählen Sie die Priorität für die Wiederherstellung der Daten aus dem Archiv-Speicher aus.
+

NOTE: Nur wenn Sie Amazon Web Services oder Microsoft Azure als Cloud-Provider verwenden, müssen Sie die Priorität angeben.

.. Wählen Sie *Speicherort ändern*.
.. Klicken Sie Auf *Weiter*.
.. Geben Sie auf der Seite Speicherzuordnung die Details zum alternativen Speicherort an, an dem die vom Objektspeicher wiederhergestellten Daten vorübergehend gespeichert werden.
.. Klicken Sie Auf *Weiter*.




 a| 
Sie möchten an einem alternativen Speicherort wiederherstellen
 a| 
.. Wählen Sie *an alternativen Speicherort wiederherstellen*.
.. Wenn sich der Snapshot im Archiv-Speicher befindet, wählen Sie die Priorität für die Wiederherstellung der Daten aus dem Archiv-Speicher aus.
+

NOTE: Nur wenn Sie Amazon Web Services oder Microsoft Azure als Cloud-Provider verwenden, müssen Sie die Priorität angeben.

.. Klicken Sie Auf *Weiter*.
.. Wählen Sie auf der Seite Ziel-Host einen Hostnamen aus, geben Sie einen Datenbanknamen an (optional), wählen Sie eine Instanz aus und geben Sie die Wiederherstellungspfade an.
+

NOTE: Die im alternativen Pfad angegebene Dateierweiterung muss mit der Dateiendung der ursprünglichen Datenbankdatei identisch sein.

.. Klicken Sie Auf *Weiter*.




 a| 
Sie möchten vorübergehend auf einem anderen Speicher wiederherstellen und die wiederhergestellten Dateien dann an einen anderen Speicherort kopieren
 a| 
.. Wählen Sie *an alternativen Speicherort wiederherstellen*.
.. Wenn sich der Snapshot im Archiv-Speicher befindet, wählen Sie die Priorität für die Wiederherstellung der Daten aus dem Archiv-Speicher aus.
+

NOTE: Nur wenn Sie Amazon Web Services oder Microsoft Azure als Cloud-Provider verwenden, müssen Sie die Priorität angeben.

.. Wählen Sie *Speicherort ändern*.
.. Klicken Sie Auf *Weiter*.
.. Geben Sie auf der Seite Speicherzuordnung die Details zum alternativen Speicherort an, an dem die vom Objektspeicher wiederhergestellten Daten vorübergehend gespeichert werden.
.. Klicken Sie Auf *Weiter*.
.. Wählen Sie auf der Seite Ziel-Host einen Hostnamen aus, geben Sie einen Datenbanknamen an (optional), wählen Sie eine Instanz aus und geben Sie die Wiederherstellungspfade an.
+

NOTE: Die im alternativen Pfad angegebene Dateierweiterung muss mit der Dateiendung der ursprünglichen Datenbankdatei identisch sein.

.. Klicken Sie Auf *Weiter*.


|===
. Wählen Sie im Feld *Pre-Operations* eine der folgenden Optionen aus:
+
** Wählen Sie *Überschreiben Sie die Datenbank mit demselben Namen während der Wiederherstellung* aus, um die Datenbank mit dem gleichen Namen wiederherzustellen.
** Wählen Sie *SQL-Datenbankreplikationseinstellungen beibehalten* aus, um die Datenbank wiederherzustellen und die vorhandenen Replikationseinstellungen beizubehalten.


. Wählen Sie im Abschnitt *Post-Operations* eine der folgenden Optionen aus, um den Datenbankstatus für die Wiederherstellung zusätzlicher Transaktionsprotokolle festzulegen:
+
** Wählen Sie *Operational, aber nicht verfügbar* aus, wenn Sie jetzt alle notwendigen Backups wiederherstellen.
+
Dies ist das Standardverhalten, das die Datenbank durch ein Rollback der nicht gesicherten Transaktionen einsatzbereit macht. Sie können erst dann weitere Transaktionsprotokolle wiederherstellen, wenn Sie ein Backup erstellen.

** Wählen Sie * nicht betriebsbereit, aber verfügbar* aus, um die Datenbank nicht betriebsbereit zu lassen, ohne die nicht gesicherten Transaktionen zurückzurollen.
+
Zusätzliche Transaktions-Logs können wiederhergestellt werden. Sie können die Datenbank erst verwenden, wenn sie wiederhergestellt ist.

** Wählen Sie *schreibgeschützter Modus und verfügbar*, um die Datenbank im schreibgeschützten Modus zu belassen.
+
Mit dieser Option werden nicht gesicherte Transaktionen rückgängig gemacht, die nicht rückgängig gemachte Aktionen werden jedoch in einer Standby-Datei gespeichert, sodass Recovery-Effekte rückgängig gemacht werden können.

+
Wenn die Option „Verzeichnis aufheben“ aktiviert ist, werden mehr Transaktionsprotokolle wiederhergestellt. Wenn der Wiederherstellungsvorgang für das Transaktionsprotokoll nicht erfolgreich ist, können die Änderungen zurückgesetzt werden. Die SQL Server-Dokumentation enthält weitere Informationen.



. Klicken Sie Auf *Weiter*.
. Überprüfen Sie die Details und klicken Sie auf *Wiederherstellen*.

