---
sidebar: sidebar 
permalink: task-create-policies-vms.html 
keywords: create policy, protection policies, predefined policies, custom policies 
summary: Erstellen Sie eine Richtlinie zum Backup von Datastores 
---
= Erstellen Sie eine Richtlinie zum Backup von Datastores
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können eine Richtlinie erstellen oder eine der folgenden vordefinierten Richtlinien verwenden, die in BlueXP verfügbar sind.

.Bevor Sie beginnen
* Sie sollten Richtlinien erstellen, wenn Sie die vordefinierten Richtlinien nicht bearbeiten möchten.
* Um die Backups vom Objektspeicher in den Archiv-Storage zu verschieben, sollten Sie ONTAP 9.10.1 oder höher ausführen und Amazon Web Services oder Microsoft Azure als Cloud-Provider einsetzen.
* Sie sollten die Zugriffsebene für den Archiv für jeden Cloud-Provider konfigurieren.


.Über diese Aufgabe
Die folgenden vordefinierten Richtlinien sind in BlueXP verfügbar:

|===
| Name Der Richtlinie | Etikett | Aufbewahrungswert 


 a| 
1 Jahr tägliche LTR (langfristige Aufbewahrung)
 a| 
Täglich
 a| 
366



 a| 
5 Jahre tägliche LTR
 a| 
Täglich
 a| 
1830



 a| 
7 Jahre wöchentlicher LTR
 a| 
Wöchentlich
 a| 
370



 a| 
10 Jahre Monatliche LTR
 a| 
Monatlich
 a| 
120

|===
.Schritte
. Wählen Sie auf der Seite Virtuelle Maschinen aus der Dropdown-Liste Einstellungen die Option *Richtlinien* aus.
. Klicken Sie auf *Create Policy*.
. Geben Sie im Abschnitt Richtliniendetails den Richtliniennamen an.
. Wählen Sie im Abschnitt Aufbewahrung einen Aufbewahrungstyp aus und geben Sie die Anzahl der zu behaltenden Backups an.
. Wählen Sie Primary oder Secondary als Backup-Speicherquelle aus.
. (Optional) Wenn Sie Backups nach einer bestimmten Anzahl von Tagen zur Kostenoptimierung vom Objektspeicher in den Archivspeicher verschieben möchten, aktivieren Sie das Kontrollkästchen *Tiering Backups in Archival* und geben Sie die Anzahl der Tage ein, nach denen das Backup archiviert werden soll.
. Klicken Sie Auf *Erstellen*.
+

NOTE: Sie können keine Richtlinie bearbeiten oder löschen, die einem Datastore zugeordnet ist.


