---
sidebar: sidebar 
permalink: task-report-inventory.html 
keywords: cloud backup, backup and recovery service, backup and recovery, backup, restore, report, inventory, bluexp 
summary: Mit den Backup- und Recovery-Berichten von BlueXP können Sie sicherstellen, dass kritische Daten gemäß den definierten Richtlinien Ihres Unternehmens geschützt sind, und Audits für Compliance-Prozesse effizient unterstützen. Mit dem Backup-Inventarbericht können Sie alle Ihre Backups für ein bestimmtes Konto, eine Arbeitsumgebung oder einen SVM-Bestand anzeigen. 
---
= Bericht zum Datenschutzumfang mit BlueXP Backup und Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Stellen Sie mit den Sicherungs- und Wiederherstellungsberichten von BlueXP sicher, dass kritische Daten gemäß den festgelegten Richtlinien Ihres Unternehmens geschützt sind, und führen Sie Audits zur Erfüllung der Compliance-Anforderungen durch.

BlueXP Backup- und Recovery-Berichte ermöglichen Ihnen Folgendes:

* *Sichtbarkeit des Betriebs*: Überwachen Sie Ihre Service-Level-Agreements in Bezug auf Datensicherung, Erfolgsquote des Backups und Anpassung der Backup-Zeitfenster an die Geschäftsanforderungen.
* *Compliance und Auditing*: Verwenden Sie Betriebs- und Bestandsberichte in Ihren internen und externen Audit-Prozessen zur kontinuierlichen Überwachung der Compliance.



NOTE: Berichtsaktivitäten werden im Job Monitoring-Protokoll überwacht, sodass Sie alle Aktivitäten überwachen können. link:task-monitor-backup-jobs.html["Erfahren Sie mehr über die Jobüberwachung"].



== Berichtsumfang

Die BlueXP Backup- und Recovery-Berichte bieten Informationen zu folgenden Aspekten:

* *Standort des Connectors*: On-premise oder in der Cloud
* *Quelle*: Cloud Volumes ONTAP-Volumes, lokale ONTAP-Volumes oder Applikationen
* *Ziel*: Jeder der Cloud-Provider, NetApp StorageGRID oder ONTAP S3
* *ONTAP-Versionen*: 9.13.0




== Erstellen Sie einen Bericht zum Backup-Bestand

Auf der Registerkarte BlueXP Backup- und Recovery-Berichte können Sie den Bericht „Backup Inventory“ erstellen und seinen Inhalt filtern. Mit dem Bericht „Backup Inventory“ können Sie alle Ihre Backups für ein bestimmtes Konto, eine Arbeitsumgebung oder einen SVM-Bestand anzeigen.

Der Bericht Backup Inventory enthält folgende Informationen und weitere Informationen:

* Konto, Arbeitsumgebung und SVM
* Geschützte und nicht geschützte Volumes
* Backup-Ziel
* Angewandte Backup-Richtlinie
* Verschlüsselungsstil (Provider-Managed Key oder benutzerverwalteter Key)
* Data Lock- und Ransomware-Sicherungsstatus (Governance, Compliance oder keine)
* Status „Archiv aktiviert“
* Anzahl der Backup-Kopien
* Backup-Typ (geplantes oder benutzerinitiiertes Ad-hoc-Backup)
* Storage-Klasse
* Snapshot-Etikett



NOTE: Der Bericht „Backup Inventory“ enthält keine Informationen zu abgelaufenen oder fehlgeschlagenen Backups.

Der obere Teil des Berichts enthält ein Diagramm mit den folgenden Informationen:

* Anzahl der im Umfang enthaltenen Volumes bei mindestens einem Backup
* Insgesamt inaktive Volumes plus aktive Volumes


Der Bericht Backup Inventory enthält die folgenden Diagramme:

* *Volume Backup Status*: Zeigt geschützte im Vergleich zu nicht geschützten Volumes für den ausgewählten Bereich an.
* *Volumen nach Backup-Anzahl*: Gruppiert Volumes nach der Anzahl der verfügbaren Backup-Kopien für dieses Volume.


.Schritte
. Wählen Sie im oberen Menü *Berichte*.
. Wählen Sie *Inventarisierung sichern*.
. Wählen Sie *Bericht erstellen*.
. Wählen Sie das Konto, die Arbeitsumgebung und die SVM aus.
+

TIP: Sie können mehrere Arbeitsumgebungen und SVMs auswählen.

. Wählen Sie den Zeitrahmen aus: Letzte 24 Stunden, Woche oder Monat.
. Prüfen Sie die Berichtsabschnitte (Snapshot-Richtlinien, Replikationsrichtlinien oder Backup-Richtlinien), abhängig von Ihrer Berichtsauswahl.
. (Optional) Filtern Sie die Ergebnisse nach Jobstatus.
. (Optional) Exportieren Sie den Berichtinhalt im CSV-Format, indem Sie *CSV herunterladen* auswählen.




== Erstellen Sie einen Aktivitätsbericht zu Datenschutzjobs

Proaktives Monitoring kann den Aufwand reduzieren, der für das Monitoring aller Ressourcen in Ihrem System erforderlich ist. Ab ONTAP 9.13.0 bietet der Bericht Aktivitäten zu Datensicherungsjobs Informationen zu Snapshot-, Backup-, Klon- und Wiederherstellungsvorgängen. Diese können Sie mit der SLA-Überwachung verwenden und die Backup- und Recovery-Raten nachverfolgen.

Der Bericht bezieht sich auf BlueXP  Backup- und Recovery-Vorgänge für Cloud Volumes ONTAP-, On-Premises- und Applikationsdaten.

Der Bericht „Data Protection Job Activity“ enthält die folgenden Informationen und weitere Informationen:

* Konto, Arbeitsumgebung und SVM
* Jobtyp (Sicherung oder Wiederherstellung)
* Ressourcenname (Volume oder Applikation)
* Aufgabenstatus
* Start- und Endzeiten und Dauer
* Richtlinienname für Backup-Jobs
* Snapshot-Etikett für Backup-Jobs


Die Diagramme oben auf der Seite zeigen die folgenden Informationen:

* Jobs nach Typ
+
** Anzahl der Backup- und Restore-Jobs von ONTAP Volumes
** Anzahl der Backup- und Wiederherstellungsjobs für Anwendungen
** Anzahl der Backup- und Wiederherstellungsjobs für virtuelle Maschinen


* Tägliche Jobaktivität


.Schritte
. Wählen Sie im oberen Menü *Berichte*.
. Wählen Sie *Data Protection Job activity*.
. Wählen Sie *Bericht erstellen*.
. Wählen Sie das Konto, die Arbeitsumgebung und die SVM aus.
. Wählen Sie den Zeitrahmen aus: Letzte 24 Stunden, Woche oder Monat.
. (Optional) Filtern Sie die Ergebnisse nach Jobstatus, Jobtypen (Sicherung oder Wiederherstellung) und Ressource.
. (Optional) Exportieren Sie den Berichtinhalt im CSV-Format, indem Sie *CSV herunterladen* auswählen.

