---
sidebar: sidebar 
permalink: task-restore-customplugin-backup.html 
keywords: restore, mount application backups, MongoDB, MySQL, PostgreSQL 
summary: Sie können SAP HANA-Datenbanken aus der Cloud auf dem lokalen SnapCenter-Server wiederherstellen. 
---
= Stellen Sie MongoDB-, MySQL- und PostgreSQL-Datenbanken wieder her
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können MongoDB-, MySQL- und PostgreSQL-Datenbanken auf einem beliebigen Host wiederherstellen.

*Schritte*

. Klicken Sie in BlueXP UI auf *Schutz* > *Sicherung und Wiederherstellung* > *Anwendungen*.
. Wählen Sie im Feld *Filter by* den Filter *Type* aus und wählen Sie im Dropdown-Menü *MongoDB*, *MySQL* oder *PostgreSQL* aus.
. Klicken Sie auf *Details anzeigen*, die der Datenbank entsprechen, die Sie wiederherstellen möchten, und klicken Sie auf *Wiederherstellen*.
. Geben Sie auf der Seite Wiederherstellungsoptionen eine der folgenden Optionen an:
+
.. Geben Sie in der NAS-Umgebung den FQDN oder die IP-Adresse des Hosts an, auf den die aus dem Objektspeicher wiederhergestellten Volumes exportiert werden sollen.
.. Geben Sie in der SAN-Umgebung die Initiatoren des Hosts an, dem die LUNs der aus dem Objektspeicher wiederhergestellten Volumes zugeordnet werden sollen.


. Wenn sich der Snapshot im Archiv-Speicher befindet, wählen Sie die Priorität für die Wiederherstellung der Daten aus dem Archiv-Speicher aus.
. Wenn nicht genügend Speicherplatz auf dem Quellspeicher vorhanden ist oder der Quellspeicher nicht verfügbar ist, wählen Sie *Speicherort ändern*.
+
Wenn Sie *Speicherort ändern* auswählen, können Sie ein Suffix an das Ziel-Volume anhängen. Wenn Sie das Kontrollkästchen nicht aktiviert haben, wird standardmäßig *_restore* an das Zielvolume angehängt.

. Klicken Sie Auf *Weiter*.
. Geben Sie auf der Seite Speicherzuordnung die Details zum alternativen Speicherort an, an dem die vom Objektspeicher wiederhergestellten Daten gespeichert werden.
. Klicken Sie Auf *Weiter*.
. Überprüfen Sie die Details und klicken Sie auf *Wiederherstellen*.


Dieser Vorgang führt nur den Speicherexport des ausgewählten Backups auf dem angegebenen Host aus. Sie sollten das Dateisystem manuell mounten und die Datenbank aufrufen. Nach der Nutzung des Volumes kann der Speicheradministrator das Volume aus dem ONTAP-Cluster löschen.
