---
sidebar: sidebar 
permalink: task-create-policies-apps.html 
keywords: policy, create, pre-canned polices, custom policies, protection policies 
summary: Erstellen Sie eigene Richtlinien zum Schutz der Applikation. 
---
= Erstellen einer Richtlinie für das Backup von Applikationen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Erstellen Sie eine Richtlinie für Backups von Applikationsdaten in der Cloud.

*Bevor Sie beginnen*

* Wenn Sie Backups vom Objektspeicher in den Archiv-Storage verschieben möchten, stellen Sie sicher, dass Sie ONTAP 9.10.1 oder höher und Amazon Web Services oder Azure als Cloud-Provider verwenden.
* Sie sollten die Zugriffsebene für den Archiv für jeden Cloud-Provider konfigurieren.


*Schritte*

. Klicken Sie in BlueXP UI auf *Schutz* > *Sicherung und Wiederherstellung* > *Anwendungen*.
. Klicken Sie im Dropdown-Menü Einstellungen auf *Richtlinien* > *Richtlinien erstellen*.
. Geben Sie im Abschnitt Richtliniendetails den Richtliniennamen an.
. Wählen Sie im Abschnitt Aufbewahrung einen Aufbewahrungstyp aus und geben Sie die Anzahl der zu behaltenden Backups an.
. Wählen Sie Primary oder Secondary als Backup-Speicherquelle aus.
. (Optional) Wenn Sie Backups nach einer bestimmten Anzahl von Tagen zur Kostenoptimierung vom Objektspeicher in den Archivspeicher verschieben möchten, aktivieren Sie das Kontrollkästchen *Tiering Backups in Archive*.
. Klicken Sie Auf *Erstellen*.
+

NOTE: Eine Richtlinie, die einer Anwendung zugeordnet ist, kann nicht bearbeitet oder gelöscht werden.


