---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, backup, restore, bluexp, bluexp backup and recovery, protection' 
summary: Erfahren Sie mehr über die Neuerungen bei BlueXP Backup und Recovery. 
---
= Was ist neu in BlueXP Backup und Recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Erfahren Sie mehr über die Neuerungen bei BlueXP Backup und Recovery.



== 14 Juli 2025

Diese BlueXP -Version für Backup und Recovery enthält die folgenden Updates.



=== Verbessertes ONTAP Volume Dashboard

Im April 2025 haben wir eine Vorschau eines verbesserten ONTAP Volume Dashboards veröffentlicht, das viel schneller und effizienter ist.

Dieses Dashboard wurde speziell für Unternehmenskunden mit hohen Workloads entwickelt. Selbst für Kunden mit 20.000 Volumes wird das neue Dashboard in weniger als 10 Sekunden geladen.

Nach einer erfolgreichen Vorschau und dem großartigen Feedback unserer Kunden machen wir es nun zur Standarderfahrung für alle unsere Kunden. Freuen Sie sich auf ein blitzschnelles Dashboard.

Weitere Informationen finden Sie unter link:br-use-dashboard.html["Anzeigen des Schutzstatus im Dashboard"].



=== Microsoft SQL Server-Workload-Unterstützung als Public Technology Preview

Diese Version von BlueXP backup and recovery bietet eine aktualisierte Benutzeroberfläche, mit der Sie Microsoft SQL Server-Workloads mithilfe der 3-2-1-Schutzstrategie verwalten können, die Sie vom BlueXP backup and recovery Dienst kennen. Mit der neuen Version können Sie diese Workloads auf dem Primärspeicher sichern, auf dem Sekundärspeicher replizieren und in einem Cloud-Objektspeicher sichern.

Sie können sich für die Vorschau anmelden, indem Sie dieses Formular ausfüllen.  https://forms.office.com/pages/responsepage.aspx?id=oBEJS5uSFUeUS8A3RRZbOojtBW63mDRDv3ZK50MaTlJUNjdENllaVTRTVFJGSDQ2MFJIREcxN0EwQi4u&route=shorturl["Vorschau des Anmeldeformulars"^] .


NOTE: DIESE DOKUMENTATION ZUM SCHUTZ VON MICROSOFT SQL SERVER-WORKLOADS WIRD ALS TECHNOLOGIEVORSCHAU BEREITGESTELLT. Mit diesem Vorschauangebot behält sich NetApp das Recht vor, Angebotsdetails, Inhalte und Zeitpläne vor der allgemeinen Verfügbarkeit zu ändern.

Diese Version von BlueXP backup and recovery enthält die folgenden Updates:

* *3-2-1-Backup-Funktion*: Diese Version integriert SnapCenter -Funktionen und ermöglicht Ihnen die Verwaltung und den Schutz Ihrer SnapCenter Ressourcen mit einer 3-2-1-Datensicherungsstrategie über die BlueXP backup and recovery .
* *Import aus SnapCenter*: Sie können SnapCenter -Sicherungsdaten und -Richtlinien in BlueXP backup and recovery importieren.
* *Eine neu gestaltete Benutzeroberfläche* ermöglicht eine intuitivere Verwaltung Ihrer Sicherungs- und Wiederherstellungsaufgaben.
* *Sicherungsziele*: Sie können Buckets in Amazon Web Services (AWS), Microsoft Azure Blob Storage, StorageGRID und ONTAP S3-Umgebungen hinzufügen, um sie als Sicherungsziele für Ihre Microsoft SQL Server-Workloads zu verwenden.
* *Workload-Unterstützung*: Mit dieser Version können Sie Microsoft SQL Server-Datenbanken und Verfügbarkeitsgruppen sichern, wiederherstellen, überprüfen und klonen. (Die Unterstützung für weitere Workloads wird in zukünftigen Versionen hinzugefügt.)
* *Flexible Wiederherstellungsoptionen*: Mit dieser Version können Sie Datenbanken im Falle einer Beschädigung oder eines versehentlichen Datenverlusts sowohl am ursprünglichen als auch an alternativen Speicherorten wiederherstellen.
* *Sofortige Produktionskopien*: Erstellen Sie platzsparende Produktionskopien für Entwicklung, Tests oder Analysen in Minuten statt in Stunden oder Tagen.
* Diese Version beinhaltet die Möglichkeit, detaillierte Berichte zu erstellen.


Weitere Informationen zum Schutz von Microsoft SQL Server-Workloads finden Sie unter link:br-use-mssql-protect-overview.html["Übersicht zum Schützen von Microsoft SQL Server-Workloads"] .



== 09 Juni 2025

Diese BlueXP -Version für Backup und Recovery enthält die folgenden Updates.



=== Updates zur Unterstützung indizierter Kataloge

Im Februar 2025 haben wir die aktualisierte Indizierungsfunktion (Indexed Catalog v2) eingeführt, die Sie bei der Datenwiederherstellung mit der Methode „Suchen und Wiederherstellen“ verwenden. Die vorherige Version verbesserte die Leistung der Datenindizierung in lokalen Umgebungen deutlich. Mit dieser Version ist der Indizierungskatalog nun in Amazon Web Services-, Microsoft Azure- und Google Cloud Platform (GCP)-Umgebungen verfügbar.

Für Neukunden ist der Indexed Catalog v2 standardmäßig für alle neuen Umgebungen aktiviert. Bestandskunden können ihre Umgebung neu indizieren, um den Indexed Catalog v2 zu nutzen.

.Wie aktivieren Sie die Indexierung?
Bevor Sie die Such- und Wiederherstellungsmethode zum Wiederherstellen von Daten verwenden können, müssen Sie „Indizierung“ in jeder Quellarbeitsumgebung aktivieren, in der Sie Volumes oder Dateien wiederherstellen möchten. Wählen Sie die Option *Indizierung aktivieren*, wenn Sie eine Suche und Wiederherstellung durchführen.

Der indizierte Katalog kann dann jedes Volume und jede Sicherungsdatei verfolgen, sodass Ihre Suchvorgänge schnell und effizient erfolgen.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-search-restore["Wiederherstellen von ONTAP-Daten mithilfe von Suche  Wiederherstellen"].



=== Azure Private Link-Endpunkte und Dienstendpunkte

Normalerweise richtet BlueXP Backup & Recovery einen privaten Endpunkt beim Cloud-Anbieter ein, um verschiedene Schutzaufgaben zu übernehmen. Diese Version bietet eine optionale Einstellung, mit der Sie die automatische Erstellung eines privaten Endpunkts durch BlueXP Backup & Recovery aktivieren oder deaktivieren können. Dies ist hilfreich, wenn Sie mehr Kontrolle über die Erstellung des privaten Endpunkts wünschen.

Sie können diese Option aktivieren oder deaktivieren, wenn Sie den Schutz aktivieren oder den Wiederherstellungsprozess starten.

Wenn Sie diese Einstellung deaktivieren, müssen Sie den privaten Endpunkt manuell erstellen, damit die BlueXP-Sicherung und -Wiederherstellung ordnungsgemäß funktioniert. Ohne die richtige Konnektivität können Sie Sicherungs- und Wiederherstellungsaufgaben möglicherweise nicht erfolgreich durchführen.



=== Unterstützung für SnapMirror zur Cloud-Resynchronisierung auf ONTAP S3

Die vorherige Version unterstützte SnapMirror to Cloud Resync (SM-C Resync). Diese Funktion optimiert den Datenschutz bei der Volumemigration in NetApp-Umgebungen. Diese Version unterstützt SM-C Resync auf ONTAP S3 sowie anderen S3-kompatiblen Anbietern wie Wasabi und MinIO.



=== Bringen Sie Ihren eigenen Bucket für StorageGRID mit

Wenn Sie Sicherungsdateien im Objektspeicher für eine Arbeitsumgebung erstellen, erstellt BlueXP Backup & Recovery standardmäßig den Container (Bucket oder Speicherkonto) für die Sicherungsdateien im von Ihnen konfigurierten Objektspeicherkonto. Bisher konnten Sie dies überschreiben und Ihren eigenen Container für Amazon S3, Azure Blob Storage und Google Cloud Storage angeben. Mit dieser Version können Sie nun Ihren eigenen StorageGRID-Objektspeichercontainer verwenden.

Siehe https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html#do-you-want-to-create-your-own-object-storage-container["Erstellen Sie Ihren eigenen Objektspeichercontainer"].



== 13 Mai 2025

Diese BlueXP -Version für Backup und Recovery enthält die folgenden Updates.



=== Neusynchronisierung von SnapMirror zu Cloud bei Volume-Migrationen

Die Funktion SnapMirror zu Cloud Resync optimiert die Datensicherung und Kontinuität bei Volume-Migrationen in NetApp-Umgebungen. Bei der Migration eines Volumes mithilfe von SnapMirror Logical Replication (LRSE), von einer lokalen NetApp Implementierung zu einer anderen oder zu einer Cloud-basierten Lösung wie Cloud Volumes ONTAP oder Cloud Volumes Service sorgt SnapMirror zu Cloud Resync dafür, dass vorhandene Cloud-Backups intakt und betriebsbereit bleiben.

Durch diese Funktion wird ein zeitaufwendiger und ressourcenintensiver Neustart des Basisplans überflüssig, sodass Backup-Vorgänge nach der Migration fortgesetzt werden können. Diese Funktion ist in Workload-Migrationsszenarien nützlich, da sie sowohl FlexVols als auch FlexGroups unterstützt. Sie ist ab ONTAP Version 9.16.1 verfügbar.

Durch die Aufrechterhaltung der Backup-Kontinuität über verschiedene Umgebungen hinweg verbessert SnapMirror to Cloud Resync die betriebliche Effizienz und verringert die Komplexität des Datenmanagements in der Hybrid Cloud und Multi Cloud.

Weitere Informationen zur Durchführung der Resynchronisierung finden Sie unter https://docs.netapp.com/us-en/bluexp-backup-recovery/task-migrate-volumes-snapmirror-cloud-resync.html["Migrieren Sie Volumes mit SnapMirror zur Cloud-Neusynchronisierung"].



=== Unterstützung für Minio-Objektspeicher von Drittanbietern (Vorschau)

Backup und Recovery von BlueXP  erweitern jetzt ihre Unterstützung auf Objektspeicher anderer Hersteller, wobei der Schwerpunkt auf Mini-Objektspeicher liegt. Mit dieser neuen Vorschaufunktion können Sie jeden S3-kompatiblen Objektspeicher für Ihre Backup- und Recovery-Anforderungen nutzen.

Mit dieser Vorschau-Version möchten wir eine robuste Integration in Objektspeicher von Drittanbietern gewährleisten, bevor die volle Funktionalität verfügbar ist. Wir empfehlen Ihnen, diese neue Funktion zu erkunden und Feedback zu geben, um den Service zu verbessern.


IMPORTANT: Diese Funktion sollte nicht in der Produktion verwendet werden.

*Beschränkungen des Vorschaumodus*

Während diese Funktion in der Vorschau angezeigt wird, gibt es einige Einschränkungen:

* Bring Your Own Bucket (BYOB) wird nicht unterstützt.
* Die Aktivierung von DataLock in der Richtlinie wird nicht unterstützt.
* Die Aktivierung des Archivmodus in der Richtlinie wird nicht unterstützt.
* Es werden nur lokale ONTAP-Umgebungen unterstützt.
* MetroCluster wird nicht unterstützt.
* Optionen zur Aktivierung der Verschlüsselung auf Bucket-Ebene werden nicht unterstützt.


*Erste Schritte*

Um diese Vorschaufunktion zu verwenden, müssen Sie ein Flag auf dem BlueXP -Konnektor aktivieren. Sie können dann die Verbindungsdetails Ihres Minio-Objektspeichers von Drittanbietern im Schutz-Workflow eingeben, indem Sie im Backup-Bereich den Objektspeicher *Drittanbieter-kompatibel* auswählen.

Anweisungen zum Aktivieren von Vorschaufunktionen finden Sie unter https://docs.netapp.com/us-en/bluexp-backup-recovery/task-preview-enable.html["Aktivieren Sie Vorschaufunktionen für BlueXP  Backup und Recovery"].



== Bis 16. April 2025

Diese BlueXP -Version für Backup und Recovery enthält die folgenden Updates.



=== UI-Verbesserungen

Diese Version verbessert die Benutzerfreundlichkeit durch die Vereinfachung der Oberfläche:

* Das Entfernen der Spalte Aggregate aus den Volume-Tabellen zusammen mit den Spalten Snapshot Policy, Backup Policy und Replication Policy aus der Volume-Tabelle im V2 Dashboard führt zu einem optimierten Layout.
* Wenn Sie nicht aktivierte Arbeitsumgebungen aus der Dropdown-Liste ausschließen, wird die Oberfläche weniger überladen, die Navigation effizienter und das Laden schneller.
* Während die Sortierung in der Spalte Tags deaktiviert ist, können Sie die Tags dennoch anzeigen, um sicherzustellen, dass wichtige Informationen leicht zugänglich bleiben.
* Das Entfernen von Etiketten auf den Schutzsymbolen trägt zu einem saubereren Aussehen bei und verringert die Ladezeit.
* Während der Aktivierung der Arbeitsumgebung wird in einem Dialogfeld ein Ladesymbol angezeigt, das Feedback liefert, bis der Erkennungsvorgang abgeschlossen ist. Dies erhöht die Transparenz und erhöht die Sicherheit für die Systemvorgänge.




=== Verbessertes Volume Dashboard (Vorschau)

Das Volume Dashboard kann jetzt in weniger als 10 Sekunden geladen werden und bietet damit eine wesentlich schnellere und effizientere Schnittstelle. Diese Vorschau-Version ist für ausgewählte Kunden verfügbar und bietet ihnen einen ersten Blick auf diese Verbesserungen.



=== Unterstützung für Wasabi-Objektspeicher von Drittanbietern (Vorschau)

BlueXP  Backup und Recovery erweitert jetzt ihre Unterstützung auf Objektspeicher von Drittanbietern, wobei der Schwerpunkt primär auf Wasabi liegt. Mit dieser neuen Vorschaufunktion können Sie jeden S3-kompatiblen Objektspeicher für Ihre Backup- und Recovery-Anforderungen nutzen.



==== Erste Schritte mit Wasabi

Um Drittanbieter-Storage als Objektspeicher zu verwenden, müssen Sie im BlueXP -Connector ein Flag aktivieren. Anschließend können Sie die Verbindungsdetails für einen Objektspeicher eines Drittanbieters eingeben und in Ihre Backup- und Recovery-Workflows integrieren.

.Schritte
. SSH in den Connector.
. Gehen Sie zum cbs-Server-Container für Backup und Recovery von BlueXP :
+
[listing]
----
docker exec -it cloudmanager_cbs sh
----
. Öffnen Sie die `default.json` Datei im `config` Ordner über VIM oder einen anderen Editor:
+
[listing]
----
vi default.json
----
. Ändern `allow-s3-compatible`: false zu `allow-s3-compatible`: true.
. Speichern Sie die Änderungen.
. Verlassen Sie den Container.
. Starten Sie den cbs-Server-Container für BlueXP  Backup und Recovery neu.


.Ergebnis
Nachdem der Container wieder EINGESCHALTET ist, öffnen Sie die BlueXP  Backup and Recovery UI. Wenn Sie ein Backup initiieren oder eine Backup-Strategie bearbeiten, wird der neue Provider zusammen mit anderen Backup-Providern von AWS, Microsoft Azure, Google Cloud, StorageGRID und ONTAP S3 als „S3-kompatibel“ aufgeführt.



==== Einschränkungen des Vorschaumodus

Während diese Funktion in der Vorschau angezeigt wird, beachten Sie die folgenden Einschränkungen:

* Bring Your Own Bucket (BYOB) wird nicht unterstützt.
* Die Aktivierung von DataLock in einer Richtlinie wird nicht unterstützt.
* Die Aktivierung des Archivmodus in einer Richtlinie wird nicht unterstützt.
* Es werden nur lokale ONTAP-Umgebungen unterstützt.
* MetroCluster wird nicht unterstützt.
* Optionen zur Aktivierung der Verschlüsselung auf Bucket-Ebene werden nicht unterstützt.


In dieser Vorschau empfehlen wir Ihnen, diese neue Funktion zu erkunden und Feedback zur Integration in Objektspeicher von Drittanbietern zu geben, bevor die volle Funktionalität bereitgestellt wird.



== 17 März 2025

Diese BlueXP -Version für Backup und Recovery enthält die folgenden Updates.



=== SMB-Snapshot-Browsing

Dieses BlueXP  Backup und Recovery Update löste ein Problem, das Kunden daran hinderte, lokale Snapshots in einer SMB-Umgebung zu durchsuchen.



=== Update zur AWS GovCloud Umgebung

Dieses BlueXP  Backup- und Recovery-Update hat ein Problem behoben, das die UI aufgrund von TLS-Zertifikatfehlern daran gehindert hat, eine Verbindung zu einer AWS GovCloud Umgebung herzustellen. Das Problem wurde behoben, indem der Hostname des BlueXP -Connectors anstelle der IP-Adresse verwendet wurde.



=== Grenzen der Aufbewahrung von Backup-Richtlinien

Zuvor beschränkte die Benutzeroberfläche von BlueXP  für Backup und Recovery Backups auf 999 Kopien, während die CLI mehr erlaubte. Jetzt können Sie bis zu 4,000 Volumes zu einer Backup-Richtlinie hinzufügen und 1,018 Volumes einbeziehen, die nicht an eine Backup-Richtlinie gebunden sind. Dieses Update enthält zusätzliche Validierungen, die eine Überschreitung dieser Grenzwerte verhindern.



=== SnapMirror Cloud-Neusynchronisierung

Dieses Update sorgt dafür, dass SnapMirror Cloud Resync nicht aus BlueXP  Backup und Recovery für nicht unterstützte ONTAP Versionen gestartet werden kann, nachdem eine SnapMirror Beziehung gelöscht wurde.



== 21 Februar 2025

Diese BlueXP -Version für Backup und Recovery enthält die folgenden Updates.



=== Hochperformante Indizierung

BlueXP  Backup und Recovery bietet eine aktualisierte Indexierungsfunktion, durch die die Indizierung der Daten in der Arbeitsumgebung der Quelle effizienter erfolgt. Die neue Indexierungsfunktion umfasst Updates der Benutzeroberfläche, eine verbesserte Performance der Methode „Search & Restore“ zur Datenwiederherstellung, Upgrades der Funktionen für globale Suchvorgänge und eine bessere Skalierbarkeit.

Hier eine Aufschlüsselung der Verbesserungen:

* *Ordnerkonsolidierung*: Die aktualisierte Version gruppiert Ordner zusammen mit Namen, die bestimmte Kennungen enthalten, was den Indizierungsprozess reibungsloser macht.
* *Parkett-Dateiverdichtung*: Die aktualisierte Version reduziert die Anzahl der Dateien, die für die Indizierung jedes Volumes verwendet werden, vereinfacht den Prozess und macht eine zusätzliche Datenbank erforderlich.
* *Scale-out mit mehr Sitzungen*: Die neue Version fügt mehr Sitzungen zur Bearbeitung von Indizierungsaufgaben hinzu, was den Prozess beschleunigt.
* *Unterstützung für mehrere Index-Container*: Die neue Version verwendet mehrere Container, um Indexaufgaben besser zu verwalten und zu verteilen.
* *Split Index Workflow*: Die neue Version unterteilt den Indexierungsprozess in zwei Teile, wodurch die Effizienz erhöht wird.
* *Verbesserte Parallelität*: Die neue Version ermöglicht es, Verzeichnisse gleichzeitig zu löschen oder zu verschieben, was den Indexierungsprozess beschleunigt.


.Wer profitiert von dieser Funktion?
Die neue Indexierungsfunktion steht allen Neukunden zur Verfügung.

.Wie aktivieren Sie die Indexierung?
Bevor Sie die Such- und Wiederherstellungsmethode zum Wiederherstellen von Daten verwenden können, müssen Sie „Indizierung“ in jeder Quellarbeitsumgebung aktivieren, in der Sie Volumes oder Dateien wiederherstellen möchten. Auf diese Weise kann der indizierte Katalog jedes Volume und jede Sicherungsdatei nachverfolgen, sodass Ihre Suche schnell und effizient erfolgt.

Aktivieren Sie die Indizierung der Arbeitsumgebung, indem Sie die Option „Indizierung aktivieren“ auswählen, wenn Sie eine Suche und Wiederherstellung durchführen.

Weitere Informationen finden Sie in der Dokumentation https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-search-restore["Wiederherstellen von ONTAP-Daten mithilfe von Suche  Wiederherstellen"].

.Unterstützte Skalierung
Die neue Indexierungsfunktion unterstützt Folgendes:

* Globale Sucheffizienz in weniger als 3 Minuten
* Bis zu 5 Milliarden Dateien
* Bis zu 5000 Volumes pro Cluster
* Bis zu 100.000 Snapshots pro Volume
* Die maximale Zeit für die Indizierung der Basislinie beträgt weniger als 7 Tage. Die tatsächliche Zeit variiert je nach Umgebung.




=== Verbesserte globale Such-Performance

Diese Version enthält auch Verbesserungen der globalen Such-Performance. Sie sehen jetzt Fortschrittsanzeigen und ausführlichere Suchergebnisse, einschließlich der Anzahl der Dateien und der Zeit, die für die Suche erforderlich ist. Dedizierte Container für die Suche und Indexierung sorgen dafür, dass globale Suchen in weniger als fünf Minuten abgeschlossen werden.

Beachten Sie die folgenden Überlegungen zur globalen Suche:

* Der neue Index wird nicht für Snapshots ausgeführt, die als stündlich gekennzeichnet sind.
* Die neue Indexierungsfunktion funktioniert nur für Snapshots auf FlexVols und nicht für Snapshots auf FlexGroups.




== 13 Februar 2025

Diese BlueXP -Version für Backup und Recovery enthält die folgenden Updates.



=== BlueXP backup and recovery Vorschauversion

Diese Vorschauversion von BlueXP backup and recovery bietet eine aktualisierte Benutzeroberfläche, mit der Sie Microsoft SQL Server-Workloads mithilfe der 3-2-1-Schutzstrategie verwalten können, die Sie vom BlueXP backup and recovery Dienst kennen. Mit der neuen Version können Sie diese Workloads auf dem Primärspeicher sichern, auf dem Sekundärspeicher replizieren und in einem Cloud-Objektspeicher sichern.


NOTE: DIESE DOKUMENTATION WIRD ALS TECHNOLOGIEVORSCHAU BEREITGESTELLT. Mit diesem Vorschauangebot behält sich NetApp das Recht vor, Angebotsdetails, Inhalte und Zeitpläne vor der allgemeinen Verfügbarkeit zu ändern.

Diese Version von BlueXP backup and recovery Preview 2025 enthält die folgenden Updates.

* Eine neu gestaltete Benutzeroberfläche, die eine intuitivere Verwaltung Ihrer Sicherungs- und Wiederherstellungsaufgaben ermöglicht.
* Mit der Vorschauversion können Sie Microsoft SQL Server-Datenbanken sichern und wiederherstellen. (Die Unterstützung für weitere Workloads wird in zukünftigen Versionen hinzugefügt.)
* Diese Version integriert SnapCenter -Funktionen und ermöglicht Ihnen die Verwaltung und den Schutz Ihrer SnapCenter -Ressourcen mit einer 3-2-1-Datensicherungsstrategie über die BlueXP backup and recovery .
* Mit dieser Version können Sie SnapCenter -Workloads in die BlueXP backup and recovery importieren.




== Bis 22. November 2024

Diese BlueXP -Version für Backup und Recovery enthält die folgenden Updates.



=== SnapLock Compliance- und SnapLock Enterprise-Schutzmodi

BlueXP  Backup und Recovery können jetzt sowohl FlexVol als auch FlexGroup On-Premises Volumes sichern, die entweder im SnapLock Compliance- oder im SnapLock Enterprise-Sicherungsmodus konfiguriert sind. Ihre Cluster müssen ONTAP 9.14 oder höher verwenden, um diese Unterstützung zu ermöglichen. Das Sichern von FlexVol Volumes mit dem SnapLock Enterprise-Modus wird seit ONTAP Version 9.11.1 unterstützt. Frühere ONTAP Versionen bieten keine Unterstützung für Backups von SnapLock Protection Volumes.

Eine vollständige Liste der unterstützten Volumes finden Sie im https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["Erfahren Sie mehr über BlueXP Backup und Recovery"].



=== Indizierung für Such- und Wiederherstellungsprozess auf der Seite Volumes

Bevor Sie Suche und Wiederherstellung verwenden können, müssen Sie „Indizierung“ in jeder Arbeitsumgebung aktivieren, aus der Sie Volume-Daten wiederherstellen möchten. So kann der indizierte Katalog die Backup-Dateien für jedes Volume nachverfolgen. Auf der Seite Volumes wird nun der Indexierungsstatus angezeigt:

* Indiziert: Volumes wurden indiziert.
* In Bearbeitung
* Nicht Indiziert
* Indizierung angehalten
* Fehler
* Nicht Aktiviert




== 27 September 2024

Diese BlueXP -Version für Backup und Recovery enthält die folgenden Updates.



=== Podman-Support unter RHEL 8 oder 9 mit Durchsuchen und Wiederherstellen

BlueXP  Backup und Recovery unterstützt jetzt über die Podman-Engine Datei- und Ordner-Restores auf Red hat Enterprise Linux (RHEL) Version 8 und 9. Dies gilt für die BlueXP -Methode „Durchsuchen und Wiederherstellen“ für Backup und Recovery.

BlueXP  Connector Version 3.9.40 unterstützt bestimmte Versionen von Red hat Enterprise Linux Versionen 8 und 9 für jede manuelle Installation der Connector-Software auf einem RHEL 8 oder 9-Host, unabhängig vom Speicherort zusätzlich zu den in genannten Betriebssystemen https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html#step-3-review-host-requirements["Host-Anforderungen erfüllt"^]. Diese neueren RHEL-Versionen benötigen die Podman-Engine anstelle der Docker Engine. Zuvor hatte BlueXP  Backup und Recovery zwei Einschränkungen, wenn die Podman-Engine verwendet wurde. Diese Einschränkungen wurden aufgehoben.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["Erfahren Sie mehr über das Wiederherstellen von ONTAP Daten aus Backup-Dateien"].



=== Die schnellere Katalogindizierung verbessert die Suche und Wiederherstellung

Diese Version enthält einen verbesserten Katalogindex, der die Baseline-Indizierung viel schneller abschließt. Dank schnellerer Indizierung können Sie die Suchfunktion und die Restore-Funktion schneller nutzen.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["Erfahren Sie mehr über das Wiederherstellen von ONTAP Daten aus Backup-Dateien"].
