= Kubernetes-Workload-Unterstützung als Public Technology Preview
:allow-uri-read: 




=== Kubernetes-Workload-Unterstützung als Public Technology Preview

Diese Version von BlueXP backup and recovery bietet Unterstützung für die Erkennung und Verwaltung von Kubernetes-Workloads:

* Entdecken Sie Red Hat OpenShift und Open-Source-Kubernetes-Cluster, unterstützt von NetApp ONTAP, ohne Kubeconfig-Dateien freizugeben.
* Entdecken, verwalten und schützen Sie Anwendungen über mehrere Kubernetes-Cluster hinweg mithilfe einer einheitlichen Steuerungsebene.
* Lagern Sie Datenverschiebungsvorgänge zur Sicherung und Wiederherstellung von Kubernetes-Anwendungen auf NetApp ONTAP aus.
* Orchestrieren Sie lokale und objektspeicherbasierte Anwendungssicherungen.
* Sichern und stellen Sie ganze Anwendungen und einzelne Ressourcen in beliebigen Kubernetes-Clustern wieder her.
* Arbeiten Sie mit Containern und virtuellen Maschinen, die auf Kubernetes laufen.
* Erstellen Sie anwendungskonsistente Backups mithilfe von Ausführungs-Hooks und Vorlagen.

