= Updates zur Unterstützung indizierter Kataloge
:allow-uri-read: 




=== Updates zur Unterstützung indizierter Kataloge

Im Februar 2025 haben wir die aktualisierte Indizierungsfunktion (Indexed Catalog v2) eingeführt, die Sie bei der Datenwiederherstellung mit der Methode „Suchen und Wiederherstellen“ verwenden. Die vorherige Version verbesserte die Leistung der Datenindizierung in lokalen Umgebungen deutlich. Mit dieser Version ist der Indizierungskatalog nun in Amazon Web Services-, Microsoft Azure- und Google Cloud Platform (GCP)-Umgebungen verfügbar.

Für Neukunden ist der Indexed Catalog v2 standardmäßig für alle neuen Umgebungen aktiviert. Bestandskunden können ihre Umgebung neu indizieren, um den Indexed Catalog v2 zu nutzen.

.Wie aktivieren Sie die Indexierung?
Bevor Sie die Such- und Wiederherstellungsmethode zum Wiederherstellen von Daten verwenden können, müssen Sie „Indizierung“ in jeder Quellarbeitsumgebung aktivieren, in der Sie Volumes oder Dateien wiederherstellen möchten. Wählen Sie die Option *Indizierung aktivieren*, wenn Sie eine Suche und Wiederherstellung durchführen.

Der indizierte Katalog kann dann jedes Volume und jede Sicherungsdatei verfolgen, sodass Ihre Suchvorgänge schnell und effizient erfolgen.

Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-restore.html["Indizierung für Suchen und Wiederherstellen aktivieren"].



=== Azure Private Link-Endpunkte und Dienstendpunkte

Normalerweise richtet BlueXP backup and recovery einen privaten Endpunkt beim Cloud-Anbieter ein, um Schutzaufgaben zu übernehmen. Diese Version bietet eine optionale Einstellung, mit der Sie die automatische Erstellung eines privaten Endpunkts durch BlueXP Backup & Recovery aktivieren oder deaktivieren können. Dies ist hilfreich, wenn Sie mehr Kontrolle über die Erstellung des privaten Endpunkts wünschen.

Sie können diese Option aktivieren oder deaktivieren, wenn Sie den Schutz aktivieren oder den Wiederherstellungsprozess starten.

Wenn Sie diese Einstellung deaktivieren, müssen Sie den privaten Endpunkt manuell erstellen, damit die BlueXP-Sicherung und -Wiederherstellung ordnungsgemäß funktioniert. Ohne die richtige Konnektivität können Sie Sicherungs- und Wiederherstellungsaufgaben möglicherweise nicht erfolgreich durchführen.



=== Unterstützung für SnapMirror zur Cloud-Resynchronisierung auf ONTAP S3

Die vorherige Version unterstützte SnapMirror to Cloud Resync (SM-C Resync). Diese Funktion optimiert den Datenschutz bei der Volumemigration in NetApp-Umgebungen. Diese Version unterstützt SM-C Resync auf ONTAP S3 sowie anderen S3-kompatiblen Anbietern wie Wasabi und MinIO.



=== Bringen Sie Ihren eigenen Bucket für StorageGRID mit

Wenn Sie Sicherungsdateien im Objektspeicher für eine Arbeitsumgebung erstellen, erstellt BlueXP Backup & Recovery standardmäßig den Container (Bucket oder Speicherkonto) für die Sicherungsdateien im von Ihnen konfigurierten Objektspeicherkonto. Bisher konnten Sie dies überschreiben und Ihren eigenen Container für Amazon S3, Azure Blob Storage und Google Cloud Storage angeben. Mit dieser Version können Sie nun Ihren eigenen StorageGRID-Objektspeichercontainer verwenden.

Siehe https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-protect-journey.html["Erstellen Sie Ihren eigenen Objektspeichercontainer"].
