= UI-Verbesserungen
:allow-uri-read: 




=== UI-Verbesserungen

Diese Version verbessert die Benutzerfreundlichkeit durch die Vereinfachung der Oberfläche:

* Das Entfernen der Spalte Aggregate aus den Volume-Tabellen zusammen mit den Spalten Snapshot Policy, Backup Policy und Replication Policy aus der Volume-Tabelle im V2 Dashboard führt zu einem optimierten Layout.
* Wenn Sie nicht aktivierte Arbeitsumgebungen aus der Dropdown-Liste ausschließen, wird die Oberfläche weniger überladen, die Navigation effizienter und das Laden schneller.
* Während die Sortierung in der Spalte Tags deaktiviert ist, können Sie die Tags dennoch anzeigen, um sicherzustellen, dass wichtige Informationen leicht zugänglich bleiben.
* Das Entfernen von Etiketten auf den Schutzsymbolen trägt zu einem saubereren Aussehen bei und verringert die Ladezeit.
* Während der Aktivierung der Arbeitsumgebung wird in einem Dialogfeld ein Ladesymbol angezeigt, das Feedback liefert, bis der Erkennungsvorgang abgeschlossen ist. Dies erhöht die Transparenz und erhöht die Sicherheit für die Systemvorgänge.




=== Verbessertes Volume Dashboard (Vorschau)

Das Volume Dashboard kann jetzt in weniger als 10 Sekunden geladen werden und bietet damit eine wesentlich schnellere und effizientere Schnittstelle. Diese Vorschau-Version ist für ausgewählte Kunden verfügbar und bietet ihnen einen ersten Blick auf diese Verbesserungen.



=== Unterstützung für Wasabi-Objektspeicher von Drittanbietern (Vorschau)

BlueXP  Backup und Recovery erweitert jetzt ihre Unterstützung auf Objektspeicher von Drittanbietern, wobei der Schwerpunkt primär auf Wasabi liegt. Mit dieser neuen Vorschaufunktion können Sie jeden S3-kompatiblen Objektspeicher für Ihre Backup- und Recovery-Anforderungen nutzen.



==== Erste Schritte mit Wasabi

Um Drittanbieter-Storage als Objektspeicher zu verwenden, müssen Sie im BlueXP -Connector ein Flag aktivieren. Anschließend können Sie die Verbindungsdetails für einen Objektspeicher eines Drittanbieters eingeben und in Ihre Backup- und Recovery-Workflows integrieren.

.Schritte
. SSH in den Connector.
. Gehen Sie zum cbs-Server-Container für Backup und Recovery von BlueXP :
+
[listing]
----
docker exec -it cloudmanager_cbs sh
----
. Öffnen Sie die `default.json` Datei im `config` Ordner über VIM oder einen anderen Editor:
+
[listing]
----
vi default.json
----
. Ändern `allow-s3-compatible`: false zu `allow-s3-compatible`: true.
. Speichern Sie die Änderungen.
. Verlassen Sie den Container.
. Starten Sie den cbs-Server-Container für BlueXP  Backup und Recovery neu.


.Ergebnis
Nachdem der Container wieder EINGESCHALTET ist, öffnen Sie die BlueXP  Backup and Recovery UI. Wenn Sie ein Backup initiieren oder eine Backup-Strategie bearbeiten, wird der neue Provider zusammen mit anderen Backup-Providern von AWS, Microsoft Azure, Google Cloud, StorageGRID und ONTAP S3 als „S3-kompatibel“ aufgeführt.



==== Einschränkungen des Vorschaumodus

Während diese Funktion in der Vorschau angezeigt wird, beachten Sie die folgenden Einschränkungen:

* Bring Your Own Bucket (BYOB) wird nicht unterstützt.
* Die Aktivierung von DataLock in einer Richtlinie wird nicht unterstützt.
* Die Aktivierung des Archivmodus in einer Richtlinie wird nicht unterstützt.
* Es werden nur lokale ONTAP-Umgebungen unterstützt.
* MetroCluster wird nicht unterstützt.
* Optionen zur Aktivierung der Verschlüsselung auf Bucket-Ebene werden nicht unterstützt.


In dieser Vorschau empfehlen wir Ihnen, diese neue Funktion zu erkunden und Feedback zur Integration in Objektspeicher von Drittanbietern zu geben, bevor die volle Funktionalität bereitgestellt wird.
