= BlueXP backup and recovery Vorschauversion
:allow-uri-read: 




=== BlueXP backup and recovery Vorschauversion

Diese Vorschauversion von BlueXP backup and recovery bietet eine aktualisierte Benutzeroberfläche, mit der Sie Microsoft SQL Server-Workloads mithilfe der 3-2-1-Schutzstrategie verwalten können, die Sie vom BlueXP backup and recovery Dienst kennen. Mit der neuen Version können Sie diese Workloads auf dem Primärspeicher sichern, auf dem Sekundärspeicher replizieren und in einem Cloud-Objektspeicher sichern.


NOTE: DIESE DOKUMENTATION WIRD ALS TECHNOLOGIEVORSCHAU BEREITGESTELLT. Mit diesem Vorschauangebot behält sich NetApp das Recht vor, Angebotsdetails, Inhalte und Zeitpläne vor der allgemeinen Verfügbarkeit zu ändern.

Diese Version von BlueXP backup and recovery Preview 2025 enthält die folgenden Updates.

* Eine neu gestaltete Benutzeroberfläche, die eine intuitivere Verwaltung Ihrer Sicherungs- und Wiederherstellungsaufgaben ermöglicht.
* Mit der Vorschauversion können Sie Microsoft SQL Server-Datenbanken sichern und wiederherstellen. (Die Unterstützung für weitere Workloads wird in zukünftigen Versionen hinzugefügt.)
* Diese Version integriert SnapCenter -Funktionen und ermöglicht Ihnen die Verwaltung und den Schutz Ihrer SnapCenter -Ressourcen mit einer 3-2-1-Datensicherungsstrategie über die BlueXP backup and recovery .
* Mit dieser Version können Sie SnapCenter -Workloads in die BlueXP backup and recovery importieren.

